### ISSUE TITLE
Learning moves may be buggy

### ISSUE THREAD

**Issue by roukaour** [Rangi42/polishedcrystal#122]
maraxus:

> You guys might wanna check wtf happens with pupitar at level 40
> Its crazyyyy
> Learns all moves at once
> And if you go to the move relearner its even crazier

![image](https://user-images.githubusercontent.com/1761576/29202650-3f4023d6-7e38-11e7-83f1-0767c805d3e7.png)

> the pupitar thing cleared after i leved it to 55 and turned to tyranitar. To mention that it was holding a lucky egg. I then transferred the lucky egg to a forretress and started grinding for lvl up and the same thing happened, trying to relearn all his moves at once
> Also this doesnt seem to happen when leveling up without the lucky egg

> Also pupitar doesnt appear anymore....

![image](https://user-images.githubusercontent.com/1761576/29202663-68c4ec50-7e38-11e7-8b64-d09d985a0733.png)

Megumi:

> Electivire was trying to level from 62 to 63 actually.  I was fighting one of the Fisherman on the route below Lavender Town, took out it's Magikarp, and this happened.  It tried to learn every move it could learn by level up.  I think it was holding Magnet.  Whenever I switched it in, it took the sprite of whatever was in last (so for a brief moment, I had a 'shiny' Feraligatr)

> I repeated the encounter a little later after resetting and everything was normal.

![image](https://user-images.githubusercontent.com/1761576/29499275-b38d4732-85db-11e7-9bb6-1adb8721d643.png)

![image](https://user-images.githubusercontent.com/1761576/29499276-b635949e-85db-11e7-9f23-7071da914d77.png)

![image](https://user-images.githubusercontent.com/1761576/29499278-b8e3efce-85db-11e7-934a-095351833334.png)

This may have been (partially?) fixed by replacing NO_MOVE in unfinished learnsets with STRUGGLE.

**Comment by Rangi42** [comment]
The move relearner part of this bug was addressed in #174, and nobody has reported "learning all moves at once" any more.
