### ISSUE TITLE
Telling the Day-Care Man you don't want an Egg makes them stop being created

### ISSUE THREAD

**Issue by roukaour** [Rangi42/polishedcrystal#139]
tameiki: "if you tell the daycare man you don't want an egg and that he can keep it, the pokemon stop producing eggs until you take one out and put it back in"

**Comment by FredrIQ** [comment]
Is this a bug? Because to me it sounds like reasonable behaviour...

**Comment by Rangi42** [comment]
If GSC already behaved that way, I don't mind leaving it as-is.

**Comment by FredrIQ** [comment]
This is in vanilla too. See Special_DayCareManOutside.AskGiveEgg
