### ISSUE TITLE
Eggs display in trade as "?????"

### ISSUE THREAD

**Issue by roukaour** [Rangi42/polishedcrystal#143]
The "appears to be abnormal" warning also applies to Eggs:

![image](https://user-images.githubusercontent.com/1761576/31447951-3c4b9c46-ae71-11e7-9952-86e72ff80f58.png)

The initial "Please wait!" popup also has a corrupt frame:

![image](https://user-images.githubusercontent.com/1761576/31447967-48ae7b8e-ae71-11e7-89a7-27a783c3f132.png)

**Comment by FredrIQ** [comment]
The "Please wait" graphical glitch does not appear to be present in current versions. However, I found at least one additional graphical glitch -- after watching the stats screen of a Pokémon. the palette flashes the wrong color. The wrong color persists if you were checking out a trade partner's mon, until you move your selector back to your own party.

**Comment by FredrIQ** [comment]
This needs to be verified after the Egg changes

**Comment by FredrIQ** [comment]
Fixed in a sense -- trading now works fine. However, the trade UI was referencing the Pokémon by species directly. This is now addressed mostly, except for the trade sequence itself.
