### ISSUE TITLE
AI spamming pointless moves

### ISSUE THREAD

**Issue by zanderb21** [Rangi42/polishedcrystal#145]
I noticed that some trainers spam pointless attacks over and over

These are 2 I noticed: 
Falkner spams roost even if HP is full
Firebreathing guy with 2 magmars north of goldenrod: spams haze constantly, he never attacked me once
Psychic guy on same route with abra/kadabra: his abra spams flash even after my pokemon's accuracy cant be further lowered

I got as far as 3rd gym so far, so there might be more examples of this

**Comment by SadisticMystic** [comment]
At least for the Abra in question, its moveset in the original game is Teleport/Flash/---/---, and the trainer data here does nothing to change that, only raises that team by one level all around so the Kadabra doesn't appear underleveled. Once accuracy has bottomed out, any move it selects is bound to be pointless.

**Comment by roukaour** [comment]
Check whether this was fixed by a64f9be14ada90e30553af66e913cbfd2abd8894

**Comment by FredrIQ** [comment]
Not seen any issues, nor have I seen any complaints of this as of late. Probably fixed by the commit mentioned above
