### ISSUE TITLE
Exiting a link trade or battle crashes

### ISSUE THREAD

**Issue by roukaour** [Rangi42/polishedcrystal#154]
`Function28b22` BSODs at this point:

```
	xor a
	ld [rSB], a
	ld [hSerialSend], a
	ld a, $1
	ld [rSC], a
	ld a, START_TRANSFER_INTERNAL_CLOCK
	ld [rSC], a
	ret
```

However, the trade or battle results do get saved.

**Comment by FredrIQ** [comment]
Just tested link battling to ensure that I didn't do something stupid for battling in general, and for me the game freezes outright -- including music. Never seen *that* before.
