### ISSUE TITLE
PP Up can cause graphical issues

### ISSUE THREAD

**Issue by roukaour** [Rangi42/polishedcrystal#158]
Ad Astra!: "Do you have any idea about what's going on with the transfer of the effect of the pp ups when changing the order of party? I mean, eventually some other pkm acquires the pps in the same attack number that has been administered to some other pkm previously. And I think that's happening, if I remember correctly, since 2.2.0."

![image](https://user-images.githubusercontent.com/1761576/34307665-44f5518c-e717-11e7-8acf-384bf6d9a598.png)

Silent S: "Does anyone here remember the PP Up bug that was in Prism? Apparently that bug is in this hack too (along with a few other still unresolved PP bugs)"

**Comment by roukaour** [comment]
This looks related:

Deokishisu: "My Feraligatr was poisoned with Toxic. This is it on the status screen after switching between an enemy Trainer's Pokemon."

![image](https://user-images.githubusercontent.com/1761576/34308063-56347534-e719-11e7-8357-65e3aef3c643.png)

**Comment by FredrIQ** [comment]
That used to happen for Pokémon that was badly poisoned. Is that what happened here?

**Comment by Rangi42** [comment]
I can't reproduce this, even with Toxic status.
