### ISSUE TITLE
Minimize and Baton Pass mess up the sprite animation

### ISSUE THREAD

**Issue by roukaour** [Rangi42/polishedcrystal#159]
Ad Astra!: "During Battle vs Valerie, her clafable used Minimize, then Batton pass; she sent Azumarril, and this bug ocurrs"

![image](https://user-images.githubusercontent.com/1761576/34307746-bc58f15c-e717-11e7-9f58-ffeb611f0a3f.png)
![image](https://user-images.githubusercontent.com/1761576/34307751-bf83a4b2-e717-11e7-9c8e-63a099072563.png)
![image](https://user-images.githubusercontent.com/1761576/34307754-c1617746-e717-11e7-837e-cd7704bce0d3.png)

**Comment by FredrIQ** [comment]
Is this issue still present?

**Comment by Rangi42** [comment]
It is not.
