### ISSUE TITLE
Knock Off prints "?" for item names

### ISSUE THREAD

**Issue by roukaour** [Rangi42/polishedcrystal#160]
![image](https://user-images.githubusercontent.com/1761576/34307856-435c1062-e718-11e7-9a65-dbfcbd3e8e0b.png)

![image](https://user-images.githubusercontent.com/1761576/34307858-460fe234-e718-11e7-9e67-3646397a10de.png)

**Comment by Rangi42** [comment]
Fixed by e133015a0889af4034022290c735275cb3862d46
