### ISSUE TITLE
Foes still have issues with Struggle and PP

### ISSUE THREAD

**Issue by roukaour** [Rangi42/polishedcrystal#166]
Koga's Muk keeps using Minimize, even after PP is used up:

![image](https://user-images.githubusercontent.com/1761576/34308215-34fa9bae-e71a-11e7-9a94-0a5aff2975a8.png)
![image](https://user-images.githubusercontent.com/1761576/34308217-369cf8ee-e71a-11e7-9f62-d9209ac1dce9.png)

(Charmy: "if you use struggle in a trainer battle (by wasting all your pp beforehand) your foe also uses struggle for some reason")

(Deokishisu: "When a Pokemon has only one move and it is disabled, it doesn't trigger Struggle. This could result in you getting stuck in an unwinnable Trainer battle.")

**Comment by FredrIQ** [comment]
Is this issue still around? I did a complete playthrough recently, and while the AI sometimes did rather odd things, it only ever did so in a "the AI is an idiot" way, never in terms of bugs.

**Comment by FredrIQ** [comment]
Cannot reproduce (there was a commit that was supposed to fix this a while back). If someone encounters this bug again, please let me know how to reproduce it.
