### ISSUE TITLE
Bug-Catching Contest Pokémon have wrong location and held item

### ISSUE THREAD

**Issue by roukaour** [Rangi42/polishedcrystal#170]
A smug Raichu: "caught a winning venomoth in the bug catching contest, when i got my party back and checked them, Heracross suddenly had a silver powder. The venomoth i caught in the contest also had a silver powder, but it had one from the moment i caught it"

![image](https://user-images.githubusercontent.com/1761576/35131929-be7dfa6a-fc96-11e7-887d-75d9d37714c3.png)

**Comment by FredrIQ** [comment]
2f3e1df fixed wrong location
3481519 fixed wrong held item
