### ISSUE TITLE
Move Reminder/Maniac has some bugs

### ISSUE THREAD

**Issue by jdthebud** [Rangi42/polishedcrystal#174]
A couple bugs found in v3.0.0-beta-a18de48 when using the Move Reminder/Maniac in Blackthorn City:

All Pokemon that have a move available to relearn can also learn Karate Chop.
The available moves are from previous evolutions as well as the current form.

Image 1 shows the end of the movelist of a L40 Tentacruel that knows Surf, Blizzard, Whirlpool, and Hidden Power.  Besides the erroneous Karate Chop, Tentacruel learns Hex at L44, but Tentacool learns it at L40.

Image 2 shows the end of the movelist of a L42 Hitmonchan that knows Strength, Mach Punch, ThunderPunch, and Bullet Punch.  Besides the erroneous Karate Chop, Tackle and Rage are not part of Hitmonchan's moveset, but they are learned by Tyrogue.

![image 1](https://user-images.githubusercontent.com/36779635/36623950-a8df738e-18be-11e8-9983-0f37ff85b1e9.png) ![image 2](https://user-images.githubusercontent.com/36779635/36623954-aca91d8a-18be-11e8-980d-33aaee8bed9c.png)

**Comment by jdthebud** [comment]
Tested with a few various evolved Pokemon, and I don't think this bug still happens in v3 build c7ebdea.

**Comment by FredrIQ** [comment]
This was apparently fixed, and isn't even relevant anymore due to rewrite of all applicable functions used
