### ISSUE TITLE
Pulse move animations are laggy

### ISSUE THREAD

**Issue by jdthebud** [Rangi42/polishedcrystal#176]
v3.0.0-beta-a18de48:

See example of Energy Ball and Dragon Pulse.  Dark Pulse also has the same issue, seems to be rooted in the ball animation that was created for these moves.  Not sure if there are any other moves that use that new animation though.

![polishedcrystal-dragon pulse](https://user-images.githubusercontent.com/36779635/36638909-2eda3b44-19b5-11e8-95c7-7003e79b2c3f.gif) ![polishedcrystal-energy ball](https://user-images.githubusercontent.com/36779635/36638911-39259ff8-19b5-11e8-8d07-789915293f6f.gif)

**Comment by jdthebud** [comment]
Flash Cannon also seems to have a similar issue with a lag near the end of the animation.

**Comment by FredrIQ** [comment]
For future reference (whenever opt is merged), this does not happen in the optimizations branch.

**Comment by Rangi42** [comment]
Then since `optimizations` will be merged eventually, this can stay as-is.
