### ISSUE TITLE
map-all.py is broken

### ISSUE THREAD

**Issue by cybershell12** [Rangi42/polishedcrystal#179]
requires a non-existant file located at data/maps/definitions.asm

**Comment by cybershell12** [comment]
Having images of all the maps is pretty important for this project i'm making: https://www.planetminecraft.com/project/pokmon-world-recreation/ (which includes areas from Polished Crystal (sorry for butchering Uraga Channel and west route 16, when i started this i mostly ignored scale and as such kanto's scale is wonky and those two routes don't really have enough place, i did fit in scary cave though)

**Comment by Rangi42** [comment]
Oh, then change the path to whatever it should be. data/maps/maps.asm I think. Haven't needed map-all.py for a long time, since maps are mostly stable and Polished Map exists for WYSIWYG editing.

**Comment by cybershell12** [comment]
yeah,the "Johto II" phase will include the new areas from Kanto. also what you suggested for map-all.py doesn't work. it just does nothing.
