### ISSUE TITLE
Game freeze when challengin Maylene (Ver. 3.0.0 beta a18de48)

### ISSUE THREAD

**Issue by Gianluca90** [Rangi42/polishedcrystal#180]
![polished crystal error](https://user-images.githubusercontent.com/17624372/38155220-bc3bfe9c-3476-11e8-8c06-cbc35592a88e.png)

I get this error whenever i challenge Maylene at Celadon Restaurant: it happens whenever she use her Magmortar

**Comment by LOuroboros** [comment]
From the hack's Discord Server:

> Rangi - 03/01/2018
> There is no issue with Magmortar.
> It was fixed quite a while ago.

Please, if you're going to report a bug that happens in a beta version, make sure to use the latest commit.
The patch that Rangi shared with that commit was released the 8 of October from 2017, it is almost 5 months old at this point.

**Comment by Gianluca90** [comment]
Sorry, i didn't know it was fixed. In my version i have this freeze: where can i download the bug-free version? In "release" it seems that a18de48 is the latest

**Comment by LOuroboros** [comment]
You have to compile it by following the instructions wrote in the INSTALL.md file.

**Comment by Gianluca90** [comment]
Ooh i didn't know i could compile a rom myself! Thanks for the info, i'm not so good on these things, so i think i will play the game avoiding that trainer and waiting for a new version. Thanks again!
