### ISSUE TITLE
Possible to rebattle Breeder Julie on Route 34 after leaving and re-entering the area

### ISSUE THREAD

**Issue by mary-kate** [Rangi42/polishedcrystal#181]
There's the rich kid on Route 34 who refuses to battle you until you've beaten all the other trainers there (which, I presume, includes the Police Officer who won't battle you during daytime). I was sure that I had beaten all the other trainers (except for the Police Officer) there so I went to talk to Breeder Julie, the trainer whose party consists of Pichu, Ditto and Togepi, and much to my surprise, she challenged me again.
When I initially entered Route 34 from Ilex Forest for the very first time, I eventually lost to Lyra and blacked out to Azalea Town's Pokécenter, which may or may not have anything to do with this.

This seems to be easily reproducible by entering Goldenrod City's Pokémon Center and having them heal your Pokémon, and returning to Route 34 afterwards.

ROM version: 3.0.0-beta (f0504ce, compiled yesterday)

**Comment by JasonPK** [comment]
Rebattling Breeders is a feature, as it's a thing in later generations. You can battle them over and over.

**Comment by mary-kate** [comment]
Ah, thanks for the explanation @JasonPK! I guess I was just a bit confused about being able to rebattle the trainer essentially _right_ away instead of on the next day or something like that. I'll close this issue since this wasn't a bug after all.
