### ISSUE TITLE
Route 34, Breeder Julie doesn't recognize that you've already battled

### ISSUE THREAD

**Issue by Violet-Hearn** [Rangi42/polishedcrystal#187]
Breeder Julie never goes into a post-battle state. As a consequence, you can't trigger a battle with the trainer above the day care who wants you to beat the other trainers on route 34.

3.0.0 beta a18de48

**Comment by Fipliptoon99** [comment]
That is a feature, you can rebattle breeders. So, each time you leave the route and enter it again, they are rematchable
