### ISSUE TITLE
Equippable items disappearing

### ISSUE THREAD

**Issue by FranktheMute** [Rangi42/polishedcrystal#188]
The version I am playing is v3.0.0-beta-a18de48, non-faithful, abilities, natures and perfect IVs on, non-nuzlocke.

I loaded my save as usual, I was surfing at Route 41 (coming from the Goldenrod Harbor side). I opened up the menu and took out an Eviolite from an Elekid. Then, still in the pokemon team menu, gave the Eviolite to a Gloom. It was a mistake, so once again via the same menu I took it out and equipped the Eviolite on a Murkrow instead.

I closed the menu, surfed around (ironically I talked to the fisherman that teaches Knock Off on my way up to Olivine), deposited the Elekid. The next part is blurry (it was late and I was sleepy) but I think I travelled to the National Park, caught and Pinsir and won the contest for a Sun Stone. Then I had a few battles on Route 41 (from Olivine side) and that's when I noticed the Eviolite wasn't equipped to my Murkrow nor was it in any other pokemon, bag section, item storage pc or in any of my stored pokemon.

Since I was sleepy I thought I might have fumbled around the menu and tossed it, but I tried tossing another item out and it actually asks for confirmation so I'm 100% sure I did not toss it. Also, user supurvegit0 claims to have something similar happen to him with an amulet coin, the circumstances of which I do not know.

**Comment by Rangi42** [comment]
@Dewourer also says this happened with Choice Specs. a18de48 is from 2017, so please try playing the new beta. I think a bug like this was fixed before.

**Comment by FredrIQ** [comment]
Fixed in 3481519 (Bug Contests messed with your 2nd pokémon's item)
