### ISSUE TITLE
Graphics glitch when exiting the battle bag

### ISSUE THREAD

**Issue by Rangi42** [Rangi42/polishedcrystal#193]
Palette 5 entry 3 (black) doesn't get cleared to white, so it's visible as the battle tiles are being redrawn. (This is the palette used for status condition icons in battle.)

![image](https://user-images.githubusercontent.com/35663410/40740472-f3150ee8-6416-11e8-96e0-64b76e2a9c6f.png)

**Comment by FredrIQ** [comment]
Fixed in 4ae968e
