### ISSUE TITLE
Possibly unown related

### ISSUE THREAD

**Issue by Kyudeci** [Rangi42/polishedcrystal#199]
polishedcrystal-3.0.0-beta-nortc-c7ebdea --Post 28 unowns
There's this glitch that started in Dim Cave after my MystriTogekiss was afflicted with a status (paralysis) and I checked the party screen in battle and it appeared where the status should've been. I do not recall which trainer,unfortunately.

Following that a random Apricorn in the Apricorn Box would become infinite and it seems all event scripts have restarted(?) In this case it started with me fighting Lyra again in New Bark Town and then Professor Elm who wanted me to choose a starter again but there were none and I was trapped in the lab.
![img_2019](https://user-images.githubusercontent.com/40282962/41446728-3d5ed70e-701f-11e8-9342-4980928ec1e0.jpg)

Lastly, my pokegear disappeared from the menu and I can no longer take the train between Kanto and Johto because it stops me from moving past the guard. 
![img_2017](https://user-images.githubusercontent.com/40282962/41446757-6f7c1bd4-701f-11e8-9d5c-748d4745f7a2.jpg)

**Comment by Rangi42** [comment]
This seems like a corrupt save file; I cannot reproduce it.
