### ISSUE TITLE
Pokemon left with the Contest attendant lose held items if you catch a Bug

### ISSUE THREAD

**Issue by Rangi42** [Rangi42/polishedcrystal#207]
"That includes mail stored in your mailbox. Can be a bit annoying as it can left you without kenya's mail."

**Comment by Rangi42** [comment]
Dare Evans: "Another strange item bug. I put Bright Powder on my Flaaffy, it died, went to take the Bright Powder off, it is now a Silver Powder. I had another Silver Powder in my inventory, if that means anything. It was definitely holding a Bright Powder though. ... Gave everyone an item and went in to the contest. The Pokemon that was in the second slot lost it's item when I got them back. Very strange. Still not sure how the Bright Powder turned into a Silver Powder though."

**Comment by Rangi42** [comment]
Dare Evans: "Well, I actually just figured out what's happening. Whatever the item slot of the Pokemon you catch is, that's what your second Pokemon's item slot will be when you get it back. Made sure the second slot Pokemon had no item, caught a Paras with Tiny Mushroom, now my second slot has Tiny Mushroom. This explains how my Bright Powder turned into Silver Powder too, since it obviously just overwrote it with the Venomoth's Silver Powder."

**Comment by FredrIQ** [comment]
Fixed in 3481519
