### ISSUE TITLE
Test sequence breaking of Suicune, Ho-Oh, and Eusine events

### ISSUE THREAD

**Issue by Rangi42** [Rangi42/polishedcrystal#208]
(1) james123: "I haven't even caught Suicune and this dude's already talking like Ho-Oh has returned."

![image](https://user-images.githubusercontent.com/35663410/44948390-a3641d80-adea-11e8-99f3-127b99e591e6.png)

(2) Not Lunos: ""Eusine is in Johto searching for Suicune", even though I already caught it. Also, Eusine literally left 1 second before interacting with the old man, saying something about Ho-Oh appearing in Bell Tower."

![2017-10-19_05-44-46](https://user-images.githubusercontent.com/35663410/44948403-cb538100-adea-11e8-9346-6c9d183f54b8.gif)

(3) chill dude: "in the route right of ecruteak, the suicune event doesn't play for me. Suicune is there, but when I use cut and get near him, he doesn't move and I can even interact with the sprite, which just gives me a text box that says "Object event.""

**Comment by FredrIQ** [comment]
Might be unrelated, but perhaps something is corrupting flags? I ended up skipping most of TR in R47 in my last playthrough (except Jessie and James). I will try to repro when back home and I have access to a debugger.
