### ISSUE TITLE
Spanish translation 

### ISSUE THREAD

**Issue by markos365** [Rangi42/polishedcrystal#209]
I'm willing to translate this to Spanish.
There are only 12 pages worth of text? Plus menus, moves, items and so on obviously. 
My coding skills are pretty poor so I need someone else to implement the thingy to switch languages in game.
Also a few guidelines on what to do exactly would be great. 
Is there gonna be big changes in text upon 3.0 release?

**Comment by Rangi42** [comment]
Let's talk on Discord about this. In short: you're better off forking Polished Crystal and making a Spanish-only version.
