### ISSUE TITLE
Navigating the party's stats can crash the game

### ISSUE THREAD

**Issue by Rangi42** [Rangi42/polishedcrystal#210]
If you just use the Up+Down arrows to scroll through their default pink pages it's okay. But using Left+Right to view other pages can cause graphical corruption or crash due to "bad memory access during OAM DMA" or "accessing echo RAM".

![image](https://user-images.githubusercontent.com/35663410/51006672-5e779280-1512-11e9-8d5b-1feec9bf2350.png)

![image](https://user-images.githubusercontent.com/35663410/51006673-60415600-1512-11e9-9a80-01ecfad81539.png)

**Comment by FredrIQ** [comment]
Fixed in a2e88ccac0ae6b71417153f3577132d0e52f2813
