### ISSUE TITLE
Type effectiveness and/or damage are incorrect

### ISSUE THREAD

**Issue by Rangi42** [Rangi42/polishedcrystal#211]
Polished S: "My Level 11 Cyndaquil failed to OHKO Bug Catcher Wade's Level 3 Weedle with Ember (it has a Modest nature). Later on, that Cyndaquil (evolved to Quilava) at Level 18 was doing a 3HKO on a trainer-owned Level 12 Paras with Ember (a move that absolutely should be a OHKO)."

CiriousJoker: "A wild slugma just oneshot my Kingdra using earth power, because apparently ground is super effective against dragon/water.   Wtf??"

![image](https://user-images.githubusercontent.com/35663410/51079097-54c76980-168f-11e9-9d4c-8ff42ec80941.png)

**Comment by FredrIQ** [comment]
Type matchups broke in a recent commit, which is fixed since. However, damage calculation remains broken, something I need to investigate.
