### ISSUE TITLE
Sprites close to map connections have different wrong appearances as you walk across the connection

### ISSUE THREAD

**Issue by Rangi42** [Rangi42/polishedcrystal#224]
![image](https://user-images.githubusercontent.com/35663410/52459543-cb8f3f80-2b33-11e9-86c8-6d6a62fd1f0b.png)

**Comment by Rangi42** [comment]
This bug occurs even for sprites that aren't directly visible across connections:

![image](https://user-images.githubusercontent.com/35663410/52483450-f6a08000-2b81-11e9-8147-d7d6b4fa33bb.png)

**Comment by FredrIQ** [comment]
Fixed in 01d5ac0 for sprites outside connection view. For sprites within view, things need to change such that sprites are dynamically loaded as they are needed, as discussed in discord.
