### ISSUE TITLE
Turnsteps interact oddly with surf -> land, and ledges

### ISSUE THREAD

**Issue by FredrIQ** [Rangi42/polishedcrystal#227]

**Comment by Rangi42** [comment]
![image](https://user-images.githubusercontent.com/35663410/52507439-844e9080-2bbf-11e9-8b67-6762788d7b09.png)

**Comment by Rangi42** [comment]
![image](https://user-images.githubusercontent.com/35663410/52527127-533e9080-2c91-11e9-97c3-796e2b3a8453.png)

**Comment by FredrIQ** [comment]
4100820 fixes what the last picture shows (the player sprite sometimes loading in the wrong vbank). The turnstep bug remains unfixed.

**Comment by FredrIQ** [comment]
Introduced when I made optimizations branch catch up with master a while back. Will continue investigating later.
