### ISSUE TITLE
The TM/HM Cancel icon lacks corners

### ISSUE THREAD

**Issue by Rangi42** [Rangi42/polishedcrystal#229]
![image](https://user-images.githubusercontent.com/35663410/52909088-0be76f80-3250-11e9-84e1-6f89cead3317.png)

This is because the graphic doesn't get reloaded as you scroll through the TM/HM pocket or a TM Mart; only the palette changes. So to hide the Cancel icon, it makes the black channel look white, which affects the corners too.

**Comment by FredrIQ** [comment]
This was a result of an older optimization you performed to prevent the TM/HM list from being exceedingly slow to scroll. I removed part of the optimization as part of general optimization ports for 60fps, etc, since it was no longer needed but was unable to find where this change was performed.
