### ISSUE TITLE
Don't overwrite PAL_OW_TREE on Route 34

### ISSUE THREAD

**Issue by Rangi42** [Rangi42/polishedcrystal#234]
It's needed for rustling grass and Fly leaves. Just use red for pink Day-Care Pokémon.

**Comment by FredrIQ** [comment]
OBJ4 and OBJ7 are unused palettes on Route 34 (purple NPC and rock/boulder), the rest are used. Those should be possible to reserve for daycare mons.

**Comment by Rangi42** [comment]
`PAL_OW_SILVER` and `PAL_OW_TREE` are both needed, for emotes and grass/leaf effects; so I might special-case Route 34 to work like this:

* leave `PAL_OW_SILVER` (OBJ5) and `PAL_OW_TREE` (OBJ6) alone
* load the gray palette into `PAL_OW_ROCK` (OBJ7)
* gray mons use OBJ7 instead of OBJ5
* pink mons use OBJ0 (red) instead of OBJ6
* teal mons use OBJ2 (green) instead of OBJ7

The player's room can still use proper colors for all Pokémon dolls. And that should apply to Hidden Grottoes too.

**Comment by FredrIQ** [comment]
Is there a good reason not to load palettes based on which mons are in the Day Care?

**Comment by Rangi42** [comment]
At the point where daycare or doll sprites objects are being created, the code is setting their palette index from 0 to 7, but the colors of each index are already loaded. It sounds like you're thinking of making mon1 always use OBJ6 and mon2 always use OBJ7, for example, and then load colors for slots 6 and 7 on demand.

**Comment by FredrIQ** [comment]
That is what I am thinking, yes (except use 4 and 7)
