### ISSUE TITLE
Pokédex Area map crashes when viewing Orange Islands

### ISSUE THREAD

**Issue by nicomotorhead** [Rangi42/polishedcrystal#236]
Hi, I begun to play Polished Crystal a few weeks ago and I have reached Kanto today. Just after I arrived Vermillion City I went east and took the ship to Beautiful Beach.
There I opened the Pokedex, selected Dugtrio (I also tried with others), checked its area and the game crashed.
The blue screen bring me here and I reporting it. Hope this info helps the improvement of the game.
Byebye!

**Comment by Rangi42** [comment]
I think this has to do with the screen now getting refreshed before all the region-related data has been set up in `_Area`, particularly `_Area.UpdateGFX`.
