### ISSUE TITLE
Leech seed, end of turn, possibly poison broken/not working as intended, others

### ISSUE THREAD

**Issue by ruvaldak** [Rangi42/polishedcrystal#237]
Leech seed has a rounding error or something, should only ever absorb/restore a minimum of 1 hp, at the moment low level Pokemon result in no hp restored.

End of turn effects are broken on various trainers - specifically seen on first rival battle and the bug catcher standing in the grass on route 31, above youngster Joey - once second enemy Mon is sent out, end of turn effects (leech seed, burn, poison, etc) don't function, completely skipping the dialogue where they deal any damage, as if they were never there.

On debug, poison was removed from player mons after every battle. Haven't checked non-debug, may be a debug feature for ease of use?

The tune played when registering a trainer into your phone never plays. I.e. after battling youngster Joey, you register him into your phone, but that victory-ish tune never plays. Happens for every trainer as far as I've seen.

**Comment by FredrIQ** [comment]
Can't reproduce the poison thing
