### ISSUE TITLE
Trainer register tune still doesn't play

### ISSUE THREAD

**Issue by ruvaldak** [Rangi42/polishedcrystal#239]
![polishedcrystal-3 0 0-beta-190301-233115](https://user-images.githubusercontent.com/15901769/53677855-718a2180-3c7c-11e9-8e60-3419fad4eda7.png)

The tune that usually plays when this message appears in vanilla crystal still doesn't ever activate. I am 1 commit behind (latest commit pushed was a645cea, I compiled right before that was pushed)

**Comment by ruvaldak** [comment]
I am using faithful

**Comment by FredrIQ** [comment]
Can't reproduce this on non-Faithful non-Nuzlocke.

**Comment by ruvaldak** [comment]
I will check non faithful on my end. Been using gambatte as well, will check on bgb

**Comment by FredrIQ** [comment]
Where did you reproduce this?

**Comment by FredrIQ** [comment]
Fixed in 4925057. Apparently only happened in Instant Text

**Comment by ruvaldak** [comment]
ah, didn't realize instant text was causing the problem
