### ISSUE TITLE
The registered item menu may cause NPCs to disappear

### ISSUE THREAD

**Issue by Rangi42** [Rangi42/polishedcrystal#240]
![image](https://user-images.githubusercontent.com/35663410/53677866-fb3ded00-3c84-11e9-8780-f27eebec6152.png)

![image](https://user-images.githubusercontent.com/35663410/53677867-fe38dd80-3c84-11e9-9d50-bacb011a12ec.png)

**Comment by FredrIQ** [comment]
Fixed in c66933b
