### ISSUE TITLE
Trade NPCs do not work, and may crash

### ISSUE THREAD

**Issue by ruvaldak** [Rangi42/polishedcrystal#241]
![polishedcrystal-3 0 0-beta-190301-234639](https://user-images.githubusercontent.com/15901769/53677879-bf068e80-3c7c-11e9-8cf0-857ce6fe7dc0.png)
Violet city, house directly left of pokemon center, red shirt npc, crash immediately when talking to him.

**Comment by ruvaldak** [comment]
I am using faithful

**Comment by Rangi42** [comment]
This happens for other trade NPCs too:

![image](https://user-images.githubusercontent.com/35663410/53677918-a9499700-3c85-11e9-8060-3000401f824a.png)
