### ISSUE TITLE
Magnitude!

### ISSUE THREAD

**Issue by ruvaldak** [Rangi42/polishedcrystal#242]
![polishedcrystal-3 0 0-beta-190302-000720](https://user-images.githubusercontent.com/15901769/53678095-03475e00-3c80-11e9-8ab8-b0b64aa62a42.png)
Magnitude! Doesn't provide the magnitude scale. Feature of nuzlocke or bug? I'm, once again, behind one commit, currently using a645cea

**Comment by FredrIQ** [comment]
Fixed in 1674db1.
