### ISSUE TITLE
Add static encounter respawn

### ISSUE THREAD

**Issue by FredrIQ** [Rangi42/polishedcrystal#245]
If you faint a static encounter, or release it (for minmaxers wanting to re-roll stats), defeating the Elite Four should make them respawn and be possible to encounter again.

**Comment by Rangi42** [comment]
This already exists; see `RespawnOneOffs` in [engine/events/specials.asm](/engine/events/specials.asm).

**Comment by FredrIQ** [comment]
Ah, my bad. Although, allowing respawn after releasing the mon would be useful as well for minmaxers/shiny hunters.

**Comment by Rangi42** [comment]
For most static encounters you can save+reset in front of them for shininess, stats, nature, etc; but for the three roaming beasts this would be neat.
