### ISSUE TITLE
Switch-out vs move use causes a desync

### ISSUE THREAD

**Issue by FredrIQ** [Rangi42/polishedcrystal#246]
If one player switches out and the other uses a move, the one using a move will fail to interpret the switch-out, causing a desync.

**Comment by njdeliberto** [comment]
I think this applies to the open issue - fighting a mareep, switched my steelix in, mareep uses thunder wave, steelix gets paralyzed. Steelix shouldn't get paralyzed

**Comment by itsdarsh** [comment]
That's actually a separate issue. As of now, thunder wave can paralyze ground types, with or without a switch out.

**Comment by Rangi42** [comment]
This is just for link battles?
