### ISSUE TITLE
Softlock via HMs

### ISSUE THREAD

**Issue by massmarines** [Rangi42/polishedcrystal#247]
If you don't catch a Flashsave before the first Gym you are basicly done with the (Nuzlock)run.

Please remove HMs from the Game but save the Moves as TMs.

Insert Keyitems like a Surfboard(Surf) or an Axe(Cut) to get though this "one and done" Hoops...

**Comment by FredrIQ** [comment]
This is fixed in git already and will be present in next official release.

**Comment by massmarines** [comment]
Ah.. ok :)
