### ISSUE TITLE
SGB borders causing Gameyob DSiwave to blue screen on booting the game

### ISSUE THREAD

**Issue by therealbungus** [Rangi42/polishedcrystal#248]
Hey there, commit 2870d01e4f317c606c704e8ce30bb222c541db53 is causing the game to no longer boot on the DSiwave version of Gameyob. I have it installed on my 3ds, and building a fork with the latest commits up to eee16f2c36fb4a195024f81550c59512ea147cd3 and the SGB borders commit removed causes the game to load again.

**Comment by Rangi42** [comment]
Can you set it to force GBC mode? Or use a different emulator?

**Comment by therealbungus** [comment]
Force GBC mode doesn't fix it, neither do any combination of the GB Modes/bios settings/SGB borders options. It loads fine in gambatte and mGBA but I prefer to use gameyob because of the SGB borders/custom border options that only the 3DS VC allows.

**Comment by therealbungus** [comment]
There was one option I missed that actually fixed it, setting

"SGB Mode" to "Prefer GBC" and
"GBC Mode" to "ON"

causes gameyob to no longer crash on loading it, but at the same also disables the SGB borders completely. So that's a workaround to get the game booting with Gameyob but doesn't really fix the issue. Could be an emulator bug, feel free to close this issue if necessary.

**Comment by Rangi42** [comment]
I'd call that fixing the issue. SGB borders with a GBC game aren't even technically possible on real hardware, so if some emulators like BGB and VBA happen to support it anyway, that's just a bonus.
