### ISSUE TITLE
Sand Stream Issue

### ISSUE THREAD

**Issue by njdeliberto** [Rangi42/polishedcrystal#253]
When your Tyranitar activates sandstream, if an opposing pokemon is defeated, the next opposing pokemon that switches in doesn't take sand stream damage. In fact, if your tyranitar activates sandstream and is defeated, the pokemon you switch in takes damage, not the opposing pokemon. Might be related to the high jump kick bug?

**Comment by FredrIQ** [comment]
Fixed some issues with weather setters switching in at the end of the turn. Now, it doesn't tick weather count or proc weather effects if this happens until the turn after.

If this behaviour is incorrect, please let me know.
