### ISSUE TITLE
Multiple battle engine bug issues

### ISSUE THREAD

**Issue by BlazeElPadrino** [Rangi42/polishedcrystal#255]
Follow up of issue #251 and #253.

https://youtu.be/K1MDQitOumI

First, Sheer Force + Life Orb is not implemented correctly, as moves that should be boosted by Sheer Force get affected by Life Orb Recoil and moves that shouldn't get the boost activate the ability's property to negate the recoil.

Also, the engine doesn't check if a Pokemon is fainted before applying any sort of recoil or passive damage, as now we have an undead NPC Pokemon brought back to life via a recovery item activating AFTER fainting triggered by the user's recoil.

**Comment by FredrIQ** [comment]
>First, Sheer Force + Life Orb is not implemented correctly, as moves that should be boosted by Sheer Force get affected by Life Orb Recoil and moves that shouldn't get the boost activate the ability's property to negate the recoil.

Fixed.

**Comment by FredrIQ** [comment]
>Also, the engine doesn't check if a Pokemon is fainted before applying any sort of recoil or passive damage, as now we have an undead NPC Pokemon brought back to life via a recovery item activating AFTER fainting triggered by the user's recoil.

An unrelated code change should've fixed this, and might have. But I added additional safeguards against this happening.
