### ISSUE TITLE
Various mechanical errors

### ISSUE THREAD

**Issue by SadisticMystic** [Rangi42/polishedcrystal#256]
I play on a 3-beta faithful build, the most recent such patch linked in the Discord. Along the way, I've noticed several mechanical interactions that work differently than I should expect from the precedent set in later official games. Some of them might be harder to implement in the established control flow of the existing codebase than others, and I may add to this list as I notice more oddities. 

- [x] If there's an AI manual switch to a Pokemon with Trace, Trace doesn't activate there in PC. Instead, it waits for the next player switch, and announces itself at that point to take the new ability you switched to. It's supposed to fire immediately no matter how the Tracer was brought in.  
- [x] Ghost-types are supposed to have an automatic Run Away effect as far as determining if they can get away from a wild battle safely  
- [x] If U-turn or Volt Switch scores a KO, experience is supposed to be handed out before you bring a new Pokemon in, and the newcomer is not supposed to be part of the experience split unless they were already tagged as having a previous stint in the active slot    
- [ ] In modern games, when trainer AI makes a manual switch, the Pokemon that were tagged as having spent time in battle against the one that switched out should be restored the next time that Pokemon comes back. PC does not honor that, so if you're trying to do switch-training on a weak piggyback, an opponent's switch completely destroys any possible benefit you can get from that, unless you somehow find away to get the piggyback in safely for one more turn.  
- [x] Acrobatics is exactly the opposite of how it should be: it gets the power boost if you are holding an item, not otherwise  
- [x] Gyro Ball appears to have a problem computing its power, and is always dealing 1 damage even when it should be much more powerful than that  
- [x] Based on extensive observation of the opponent's switching patterns in several battles that dragged out for a while, I have a high degree of confidence that trainer AI's decisions on whether to switch at all, and if so what to bring out, are being delayed until they have received undue foreknowledge of what the player has committed to that very same turn as far as their own switch  
- [x] It is possible for an opposing trainer to use Pursuit on the player's switch and still go on to use an item in the very same turn, if they were planning on using an item (possibly related: in the case where this behavior was observed, Pursuit hit into Gengar and tripped Cursed Body, so that might have caused them to forget they had already used the move in the middle of the turn)  
- [x] When one player goes first with U-turn or Volt Switch and the other had selected Pursuit, Pursuit is supposed to happen after U-turn's damage (assuming it didn't KO) but before the switch, and be double power; current PC behavior causes Pursuit to hit after the switch in this case  
- [x] When Synchronize fires on a Toxic, it's supposed to pass back a toxic status, but PC is causing *paralysis* to be passed back instead   
- [x] Speed Boost is triggering on the same turn that the Pokemon comes in via a switch or even after replacing a fainted teammate; it should not do so in either of these cases, only at the conclusion of a full turn cycle where that Pokemon was constantly active from beginning to end   
- [x] Shell Bell should not display a message if its holder already has full HP when it deals damage  
- [ ] Future Sight is no longer typeless, and should respect immunities. It worked otherwise in original Crystal, but this is part of the overarching project of adopting a modern-style battle engine.  
- [x] Draining moves should be capped in their recovery by how much HP the target actually had left to lose, if they would otherwise calculate that they were due for some overkill damage. Likewise.

**Comment by FredrIQ** [comment]
Looks like AI switch/item use is checked after the player is already done switching out, and after the AI has also committed to using a move. This explains the AI switching based on what you switched into, and the Pursuit vs AI item/switch bug.

I'm also fairly sure this is a vanilla quirk, and ought to be investigated further there as well.

**Comment by FredrIQ** [comment]
AI item/switch behaviour should now work properly

**Comment by Rangi42** [comment]
The remaining two enhancement points have their own issues.
