### ISSUE TITLE
Kanto starters as a setting at the beginning of the game.

### ISSUE THREAD

**Issue by CiriousJoker** [Rangi42/polishedcrystal#259]
I really hate the johto starters, every one of them. Could you maybe implement a switch at the beginning of the game that changes every occurence of the johto starters/evolutions (including the rival) with their counterpart?

Given that they're in the same order, could the id just be subtracted with 151? The movepool would have to be altered as well though :/

How easy / hard is it to implement something like this with and without the Rival's pokemon changing?

**Comment by CiriousJoker** [comment]
Also, a branch with everything changed would be nice. So people could just compile their own version until an ingame solution is found.

**Comment by TheFakeMateo** [comment]
If you want to download the source and edit it for personal use, go ahead. But there is no reason for this to be an official build or new-game option, sorry.

**Comment by nephitejnf** [comment]
For future posterity
https://github.com/nephitejnf/polishedkantocrystal
