### ISSUE TITLE
Incorrect sound effect in Sprout Tower

### ISSUE THREAD

**Issue by Rangi42** [Rangi42/polishedcrystal#261]
When Silver battles the Elder, it uses an elevator sound instead of a tackle.

Monkiikong: "The audio bug exists in pokecrystal too. The code was changed 5 years ago or so. Name of sound effect used to be "$006e" and I assume someone went through and changed each instance of "$006e" and replaced it with "SFX_ELEVATOR"."

**Comment by FredrIQ** [comment]
Fixed by itsdarsh in a previous commit
