### ISSUE TITLE
Teleport while Transformed crashes

### ISSUE THREAD

**Issue by Rangi42** [Rangi42/polishedcrystal#263]
probe: "unknown opcode error game hangs when opponent ditto transform into abra and it uses teleport"

**Comment by itsdarsh** [comment]
Not able to duplicate this on commit 663f119, if anyone else gets a game crash related to this I would appreciate more information, otherwise this can probably be closed.

**Comment by Rangi42** [comment]
I also can't replicate this.

![image](https://user-images.githubusercontent.com/35663410/70291072-0c81d000-17a8-11ea-9112-21f5f094ec6d.png)

Transform+Teleport works whether it's used by a wild, trainer, or player Pokémon.
