### ISSUE TITLE
Low Kick sometimes freezes

### ISSUE THREAD

**Issue by jeffcarbine** [Rangi42/polishedcrystal#267]
When the player’s Pokémon uses Low Kick, periodically the game will either delay the attack and animation for a few seconds, or the attack and animation never fire, softlocking the game.

**Comment by FredrIQ** [comment]
Whatever it does right now, it clearly doesn't do the right thing.

**Comment by FredrIQ** [comment]
Should be fixed in recent revisions. Please reopen if this is not the case.
