### ISSUE TITLE
Poison Overworld Hurts Clefable

### ISSUE THREAD

**Issue by njdeliberto** [Rangi42/polishedcrystal#284]
Clefable isn’t hurt in battle, like Magic Guard is supposed to work, but when you walk around outside of battle its health whittles

**Comment by itsdarsh** [comment]
That's actually how Magic Guard works. https://bulbapedia.bulbagarden.net/wiki/Magic_Guard_(Ability)

> Magic Guard has no effect outside of battle. This means a poisoned Pokémon with Magic Guard will still take damage in the field in Generation IV (but not later generations, because poison no longer causes damage in the field starting in Generation V).

**Comment by FredrIQ** [comment]
But Poison Heal also works contrary to official games (where it still hurts the Pokémon -- which makes no sense). So I'm fixing this anyway.
