### ISSUE TITLE
Trainer battle intro tiles use XYflip of the tiles they replace

### ISSUE THREAD

**Issue by pkmncoraldev** [Rangi42/polishedcrystal#286]
During the flashing intro to a trainer battle, the tiles that make up the Pokeball image end up using the XYflip values of the tiles they are drawn over. It's only noticeable for the Y value, but I'm pretty sure it is taking the X value as well.

**Comment by Rangi42** [comment]
![image](https://user-images.githubusercontent.com/35663410/70290557-48b43100-17a6-11ea-9e0c-ad09a142b19f.png)
