### ISSUE TITLE
switch is botched when opponent switches in same turn

### ISSUE THREAD

**Issue by itsdarsh** [Rangi42/polishedcrystal#313]
J. Alex, aka The Huntress:
"Found another issue in my current playthrough, that I think should be checked.
I'm using a nightly build dated November 30th, 2019:
During a battle, namely vs Lyra outside Mt. Mortar...
I started with a Pokémon (I think it was my Weepinbell), and then I wanted to switch it out to my Flaaffy.
Lyra's AI decided to switch out at the same time. She sent out her next Pokémon, and then I sent out mine. However, the game sent out my Pidgeotto, even if I selected my Flaaffy. I don't know what happened here..."

I can confirm this is still an issue as of the December 7th build, and it's most likely because of my U-turn fix a while ago overwriting wCurPartyMon with enemy mon info and not setting it back to player mon info. Naturally, this would also cause major problems in link battles, where players are much more likely to run into this. However, due to an impending refactor of switch mechanics, I don't plan on addressing this on this current build. I'm posting this here more for posterity's sake, and to remember to test for this after the refactor. (note: for testing purposes, opponent switches can be forced fairly reliably by setting wEnemyPerishCount to $01)

**Comment by FredrIQ** [comment]
This bug should no longer exist after switch-out refactor. I have yet to confirm this, though.

**Comment by FredrIQ** [comment]
Works fine
