### ISSUE TITLE
Egg pics/animations are not always correct

### ISSUE THREAD

**Issue by Rangi42** [Rangi42/polishedcrystal#337]
Example: in Bill's PC → Deposit PKMN → Egg → Stats:

![image](https://user-images.githubusercontent.com/35663410/70957882-85edae00-2045-11ea-9c7e-209eafd318b6.png)

(This is after d1e2e0c3cea65eb63188d2e4d06e3ff1a1561318.)

**Comment by Rangi42** [comment]
This frontpic's color (shiny green) matches the color of the menu icon, noted in#334, so those are probably related.

**Comment by FredrIQ** [comment]
Stats screen should always be ok now. I will test trading once I get to Goldenrod.

**Comment by FredrIQ** [comment]
All known cases has been fixed. Reopen, or just make a more specific issue, if more is found
