### ISSUE TITLE
Leer lowers user's Defense instead of the opponent

### ISSUE THREAD

**Issue by THTB614** [Rangi42/polishedcrystal#339]
As stated in the title, Leer is doing the opposite effect and is lowering the user's Defense stat.

**Comment by Rangi42** [comment]
Dare Evans: "Seems like Growl is also doing the opposite, if it's not just a global thing across all stat changing moves."

**Comment by Rangi42** [comment]
When my Totodile uses Leer, the animation comes from the foe's side, and it says "Foe Cinder used Leer! Totodile's Defense fell!" So the attack works, but the sides are swapped.
