### ISSUE TITLE
Crashes during fight

### ISSUE THREAD

**Issue by silenc3r** [Rangi42/polishedcrystal#341]
OS: OpenSUSE Tumbleweed
Emulator: VisualBoyAdvance-M 2.1.0

The game crashes *frequently* during fights, on opponents turn when game is sped up.
I can't confirm whether crashes occur when playing at normal speed.

I tried bisecting first bad commit but it isn't that easy. The last working commit was 01359f1f0 and bug was *most likely* introduced before f1f9b901e

**Comment by Rangi42** [comment]
Does this also happen in BGB or Gambatte? VBA is known for inaccurate emulation. Also try the latest VBA-M 2.1.4 release. <https://github.com/visualboyadvance-m/visualboyadvance-m/releases>

**Comment by flempa316** [comment]
This is an issue I can replicate 100% of the time on VBA, it's definitely a emulator issue.

**Comment by Rangi42** [comment]
Does it still happen on 2.1.4? And does it *ever* happen in BGB or Gambatte? If it's just "VBA when sped up", I'm closing this as an emulator bug. If not, then a fix would be nice, but using a better emulator is a sufficient workaround for now.

**Comment by flempa316** [comment]
So I'm not sure if it no longer happens on 2.1.4 VBA but I can say with extremely high certainty (a full playthrough up to beating Green)that it can not be replicated on Gambatte.

**Comment by flempa316** [comment]
Was no longer able to consitently (or at all) replicate this bug on VBA 2.1.4

**Comment by Rangi42** [comment]
Thanks.
