### ISSUE TITLE
Stats being raised or lowered have no animation

### ISSUE THREAD

**Issue by Rangi42** [Rangi42/polishedcrystal#347]
Formerly the screen would shake when stats were lowered.

Ideally there would be an animation like the one when a Berry is used, but with the dot/sphere sprites rising up/down instead of circling in.

**Comment by FredrIQ** [comment]
This was kind of intentional since I found the existing one pointless. Do you prefer it over no animation at all?

**Comment by MandL27** [comment]
Stat modifiers have had animations in every game since. Some animation is better than no animation.

**Comment by Rangi42** [comment]
Animations now exist; they just need to be disabled when the Battle Effects option is off.
