### ISSUE TITLE
Game crashes during Azalea Town rival fight/Azalea Town rain pallet is wrong

### ISSUE THREAD

**Issue by THTB614** [Rangi42/polishedcrystal#352]
Not sure if this is related to rain or just the fight itself, but the game crashes after the rain starts in the rival battle in Azalea Town.

Also, the pallet for Azalea Town during rain is weird after returning to Kurt's house after the Slowpoke Well.

**Comment by Rangi42** [comment]
Are you using the HGSS build? Its colors are incomplete.

I'll look into the in-battle crash.

**Comment by THTB614** [comment]
Yes I am.  That would explain that, then.

**Comment by Rangi42** [comment]
Moving the crash part to #353.
