### ISSUE TITLE
Weather crashes in battle

### ISSUE THREAD

**Issue by Rangi42** [Rangi42/polishedcrystal#353]
Nick the Trainer: "Had a crash during the battle with the Shiny Bellossom in Olivine's Pokemon Center. It used Sunny Day, my Vulpix retaliated with Ember, it went to this screen instantly for a bit and then a frozen white screen. No cheats used or anything, not sure what caused it."

![image](https://user-images.githubusercontent.com/35663410/71416512-c0031500-262e-11ea-9d27-1d43e7ce59f7.png)

**Comment by Rangi42** [comment]
THTB614: "Not sure if this is related to rain or just the fight itself, but the game crashes after the rain starts in the rival battle in Azalea Town."

**Comment by FredrIQ** [comment]
Fixed
