### ISSUE TITLE
Phone call after 16th badge to explain Mt. Silver

### ISSUE THREAD

**Issue by Rangi42** [Rangi42/polishedcrystal#357]
Just Oak saying that after you rematch the League, you'll be ready for another challenge.

**Comment by vulcandth** [comment]
It doesn't appear that currently oak hands out his number. Would you like him to give the player his number? If so, when? Or would you rather Professor Elm make the call? I've been looking at some easy things to help out, thought I could build the shell for this with some approximate dialogue that you can tweak to your liking.

**Comment by Rangi42** [comment]
Resolved in 1ecb76e7d07e17afdca0e67d096d1d473d7defe2.
