### ISSUE TITLE
Resetting the initial game options keeps occurring

### ISSUE THREAD

**Issue by Rangi42** [Rangi42/polishedcrystal#359]
Press Left+B at the title screen to reset the initial game options. You'll be able to choose different options, but even after you Save, the menu keeps coming back.

Resetting the clock with Down+B does not have this issue; Saving will remember that the time is now set.

**Comment by FredrIQ** [comment]
I cannot reproduce this. Are you sure you saved ingame afterwards?

**Comment by Rangi42** [comment]
Yes. I'm using BGB 1.5.7.

The problem actually continues even when I start a new game; if the previous save had reset the initial options, then saving the new game and reloading will still show the options after Continue.

Possibly it's an issue with my emulator's files, not the game.

**Comment by FredrIQ** [comment]
Does last commit fix the problem? Only pressing Done reset this flag before, now it resets no matter how you leave the menu

**Comment by Rangi42** [comment]
Yes, it's fixed! Thanks for noticing that.
