### ISSUE TITLE
Add animation for critical captures

### ISSUE THREAD

**Issue by Rangi42** [Rangi42/polishedcrystal#364]
"When a critical capture occurs, the Poké Ball will make a high-pitched whistling sound as it is thrown, then pause in mid-air, and shudder before it drops down to the ground, shaking only once on the ground before the Pokémon escapes or is caught."

Adding a whistling SFX to the standard one-shake animation would work.

**Comment by FredrIQ** [comment]
Shake effect implemented in 45295f93b5, sound effect in 8655af5b952dfaf.
