### ISSUE TITLE
Fix Curse TM palette

### ISSUE THREAD

**Issue by Rangi42** [Rangi42/polishedcrystal#368]
"it uses the "pure-color" ??? type rather than the FRLG dual"

**Comment by FredrIQ** [comment]
To clarify: FRLG types either have one color, or reuse 2 colors. For example, Dragon reuses Water (top) + Fighting (bottom). For Curse, it reuses Ice (top) and Psychic (bottom).

**Comment by Rangi42** [comment]
TM03 Curse uses the same Ghost-type palette as other such TMs:

![image](https://user-images.githubusercontent.com/35663410/71937400-3bf67480-317a-11ea-83d5-6cac18561d5e.png)

**Comment by Rangi42** [comment]
The type icon palette is also correct:

![image](https://user-images.githubusercontent.com/35663410/71937610-e66e9780-317a-11ea-8071-b25ec6dfb8ab.png)

**Comment by Rangi42** [comment]
Unlike Curse, Hidden Power is a ???-type move, but its palettes are also correct:

![image](https://user-images.githubusercontent.com/35663410/71937736-39484f00-317b-11ea-93ee-4533144c3484.png)
