### ISSUE TITLE
Revise some abilities, including Mega Launcher and Tough Claws

### ISSUE THREAD

**Issue by Rangi42** [Rangi42/polishedcrystal#370]
- [x] Mega Launcher
- [x] Tough Claws

Ability plans:

- Charizard: A1 = Blaze, A2 = Solar Power, HA = Tough Claws (HA = Drought in faithful)
- Blastoise: A1 = Torrent, A2 = Rain Dish, HA = Mega Launcher
- Aerodactyl: A1 = Rock Head, A2 = Unnerve, HA = Tough Claws (non-faithful only)

**Comment by FredrIQ** [comment]
Fixed
