### ISSUE TITLE
Eviolite, Moxie, and Defiant are currently dysfunctional.

### ISSUE THREAD

**Issue by the-s-is-silent** [Rangi42/polishedcrystal#384]
The issues with the above item + abilities have been around for at least a few commits, possibly a lot longer in the case of Eviolite. I noticed last night that my Misdreavus was taking more damage than it should have while holding the Eviolite, so I made a save state to test damage calculations, using one of the Rocket Grunts in the Hideout in Mahogany Town. In both of the loaded battles, one without the Eviolite equipped to Misdreavus and one with, Misdreavus took the same amount of damage from that Grunt's Venomoth's attacks. Eviolite is not boosting defenses like it should. This was on commit 77df797e.

In the same commit, Moxie was also broken, failing to trigger at all after each KO scored by the Red Gyarados which I had soft resetted until obtaining one with the ability. I think this is also not the first time during beta testing that Moxie has not functioned correctly?

Another stat boosting ability that did not work at all was Defiant. It did not proc on any attack or ability from any foes that lowered the stats of a Farfetch'd that was bred to have its HA. This issue was encountered on commit 4a54980b.

Due to certain...difficulties, the only emulator I was able to use is MyOldBoy, which is notably not one of the more accurate Android emulators, so I am considering the chance that it could be an emulator specific issue. Though something like this sounds like it shouldn't be one of those issues.

**Comment by FredrIQ** [comment]
Fixed all the mentioned issues. Thanks!
