### ISSUE TITLE
Sprite issues with Red Gyarados's offspring.

### ISSUE THREAD

**Issue by the-s-is-silent** [Rangi42/polishedcrystal#385]
Last night, upon discovering that the Moxie ability was broken again after soft resetting at the Lake of Rage for a Red Gyarados with that ability (see my previous post for that), I attempted to breed a replacement Gyarados using that Red Gyarados that had the regular abilities. However, the sprite for the resulting Magikarp offspring was corrupted.

The issue persists on the most recent commit at the time of this report, 74b86938.
![Screenshot_20200204-174806_My OldBoy!](https://user-images.githubusercontent.com/45212764/73806451-638f2b80-477e-11ea-80c6-457a81988586.jpg)

**Comment by FredrIQ** [comment]
Moxie, Defiant, etc, actually worked fine, I merely accidentally added the "don't show stat increase message" flag for those stat changes.
