### ISSUE TITLE
Damage influenced by weather may be incorrect

### ISSUE THREAD

**Issue by Rangi42** [Rangi42/polishedcrystal#391]
abradolf: "Sandstorm currently decreases SpD as opposed to increase it. That or Whitney's Jigglypuff's Disarming Voice does extra damage when Sandstorm's up."

**Comment by FredrIQ** [comment]
Debugging this shows that Defense seem to adjust correctly. Can I get a scenario which reproduces this? Preferably with a save?

**Comment by FredrIQ** [comment]
There was an issue with Fire-types recently that turned out to be register overwriting related. Probably fixed this too, so I'll close this for now.
