### ISSUE TITLE
Lance's kingdra has 100 percent crit ratio

### ISSUE THREAD

**Issue by marrenia** [Rangi42/polishedcrystal#396]
Lance's kingdra after only one focus energy, now has 100 percent crit ratio for the rest of the fight. I looked up how focus energy is supposed to work in gen 6 and it's not supposed to make it a 100 percent crit ratio with only one use

**Comment by SadisticMystic** [comment]
https://github.com/Rangi42/polishedcrystal/blob/288a53c77921c1c10cd84661c0887328f1aba0e1/data/trainers/parties.asm#L658-L659

Kingdra has a Scope Lens, which adds the third critical stage necessary to reach 100%.

**Comment by marrenia** [comment]
Ah thanks for the clarification
