### ISSUE TITLE
Strength affects the move selection cursor

### ISSUE THREAD

**Issue by Rangi42** [Rangi42/polishedcrystal#398]
Silent S: "If any party members know Strength, in trainer battles the cursor in the move selection menu will automatically be over the slot Strength is in instead of starting at the top move. Using a healing item on the Strength user in battle causes the cursor to go back to that move instead of staying on whichever move you used last on the next turn, if it wasn't Strength. This doesn't happen in wild battles."

**Comment by FredrIQ** [comment]
Fixed in 17c39c1
