### ISSUE TITLE
Evolution Stone+move glitch

### ISSUE THREAD

**Issue by Rangi42** [Rangi42/polishedcrystal#402]
batterio: "Arcanine became water type when evolved with a Staryu in the team, but only when , if asked about a Staryu level up move after his evo move, i didn't outriht tell not to learn"

![image](https://user-images.githubusercontent.com/35663410/75355265-3b29b700-587c-11ea-8466-99e077ca1d7f.png)

**Comment by FredrIQ** [comment]
This is an old bug. Has it reappeared? What revision was this on?

**Comment by Rangi42** [comment]
If you fixed a bug like this before, it was probably an old report.
