### ISSUE TITLE
Graphics aren't fully cleared in circumstances involving Explosion, Dig, and X items

### ISSUE THREAD

**Issue by Rangi42** [Rangi42/polishedcrystal#403]
abradolf: "Battle begins; I order my mon to use Dig; enemy trainer uses X Speed on his mon; my mon digs a hole and is invulnerable; enemy mon uses Explosion and KOs itself and upper side of the screen whites out/clears up as normal; in addition to the bar that indicates how many mons the enemy trainer has left, the depleted HP bar and the sprite of the enemy that had just used Explosion overlay. things go back to normal once the next enemy mon enters the battle.

I've replicated this several times and it only happen under those circumstances. Everything works as intended when X Special isn't used, when my mon isn't temporarily invulnerable or when Explosion knocks my mon out as well."

**Comment by FredrIQ** [comment]
I don't understand move animation code enough to fix this on my own.

**Comment by flempa316** [comment]
fixing issue #466 fixed this (i think its the same issue described differently @Rangi42 )

**Comment by FredrIQ** [comment]
Yeah I'm pretty sure they're the same bug in different circumstances.
