### ISSUE TITLE
Hatched Pokémon may be named "Egg"

### ISSUE THREAD

**Issue by Rangi42** [Rangi42/polishedcrystal#405]
SchismV: "Hatching alot of pokemon leads to the name of that pokemon being named egg"

![image](https://user-images.githubusercontent.com/35663410/75613106-daa6ae00-5af7-11ea-8e1b-9e054d831094.png)

**Comment by Rangi42** [comment]
Polished Raichu: "i had that happen on a recent build of just going into the nickname screen of a newly hatched mon, and then exiting back out, instead of the new pokemon not having a nickname, it was nicknamed "egg""

**Comment by Rangi42** [comment]
Anonyboy: "Eggs kinda keep the name Egg after hatching"

![image](https://user-images.githubusercontent.com/35663410/77236418-a2453d80-6b94-11ea-91d1-dadd8a20845c.png)

**Comment by FredrIQ** [comment]
Fixed in b95ed4b
