### ISSUE TITLE
Quick Ball might not work

### ISSUE THREAD

**Issue by Rangi42** [Rangi42/polishedcrystal#409]
Gabe. Gabe? Gabe!: "My no-catch streak with the Quick Ball is now at 20-0"

Thotsandprayers: "I’ve never had a quickball work"

Skywalker200037: "for some reason, even with a pixel of health left, Im barely getting shakes even with the 4x quick balls"

**Comment by FredrIQ** [comment]
Pixilate is now fixed.

**Comment by Rangi42** [comment]
```
QuickBallMultiplier:
; multiply catch rate by 5 on first turn
	ld a, [wPlayerTurnsTaken]
	and a
	ret nz

	ln a, 5, 1 ; x5
	jp MultiplyAndDivide
```

`MultiplyAndDivide` (formerly `ApplyDamageMod`) reliably works in many other places. `[wPlayerTurnsTaken]` does start at 0 and increment every turn. And its value is read correctly here, i.e. it's not reading the wrong WRAM bank.

**Comment by FredrIQ** [comment]
Just debugged Quick Balls. They appear to function correctly.

A Poké Ball vs a level 10 Snubbull was displaying a final capture rate of 0x3F (meaning a 59/256 chance of breaking free every nudge).

Meanwhile, a Quick Ball had a final capture rate of 0x013c, which is (taking into account that both of those results probably have slight rounding errors) 5x the rate of a Poké Ball. A final capture rate of 0xFF is returned after clamping it to one byte, which tells the capture function to gurantee the capture.
