### ISSUE TITLE
Crash in Cherrygrove

### ISSUE THREAD

**Issue by ChaiKoopa** [Rangi42/polishedcrystal#410]
just started playing and when I went into Cherrygrove there was a guy inside of the pokestore tiles, when I went to go talk to him it sent my to the Pokemon Polished Crystal Error Screen
![he in the wall](https://user-images.githubusercontent.com/62034622/76355476-be222700-62ea-11ea-9b43-157a8b975961.PNG)

![pkmn polished crystal crash](https://user-images.githubusercontent.com/62034622/76355530-d6924180-62ea-11ea-84bc-d3230d8ebe0d.PNG)

**Comment by Rangi42** [comment]
If you literally *just* started playing, that might have been the update from an hour ago, which was fixed half an hour ago. ;) Wait a few minutes for the latest version to build, then please try again.
