### ISSUE TITLE
Disable should not wear off early if Struggle is the only option

### ISSUE THREAD

**Issue by Rangi42** [Rangi42/polishedcrystal#414]
SadisticMystic: "If a Pokemon has a Disabled move that still has PP left and all its other moves run out of PP, Disable is forcefully ending early even if it hasn't been 4 turns yet (this is wrong, it should go to Struggle until the Disable is over)"

**Comment by Rangi42** [comment]
This was observed in "the last one that's still save-compatible with the 3.0b branch as it was the start of 2019", so it may be fixed already.

**Comment by FredrIQ** [comment]
Encore and Disable was refactored in February, so this bug should be obsolete. Also checked relevant code; Encore immediately ends if PP runs out, but Disable does not, just like intended.
