### ISSUE TITLE
AI can choose moves with no PP left

### ISSUE THREAD

**Issue by Rangi42** [Rangi42/polishedcrystal#416]
SadisticMystic: "Blue's AI has such an obsession with picking Ice Beam on Blastoise that he'll continue picking it even when Ice Beam is out of PP and all the other moves aren't, which clearly shouldn't be allowed."

![image](https://user-images.githubusercontent.com/35663410/76690954-c72d3400-661b-11ea-948b-667aa48fb95e.png)

**Comment by Rangi42** [comment]
This was observed in "the last one that's still save-compatible with the 3.0b branch as it was the start of 2019", so it may be fixed already.

**Comment by Rangi42** [comment]
FIQ: "I believe #416 might be due to AI replacing its move score table with garbage upon checking HP, which I fixed some time ago, but I will not close it until I've confirmed it is working correctly."

**Comment by FredrIQ** [comment]
This bug does no longer appear to exist. Likely fixed as part of moving the AI score buffers to avoid some calls touching the same RAM
