### ISSUE TITLE
Multi-hit moves continue after a status condition should stop them

### ISSUE THREAD

**Issue by Rangi42** [Rangi42/polishedcrystal#417]
Dare Evans: "I just had Fury Strikes hit Paras with Effect Spore, put me to sleep on the first hit, and then continue hitting while asleep. Not sure if it's a big deal but it's funny. Build e5872245"

SadisticMystic: "canonical behavior is that sleep automatically ends the move"

**Comment by FredrIQ** [comment]
Fixed in c63080c
