### ISSUE TITLE
Weather icon can overlap text in battle

### ISSUE THREAD

**Issue by Rangi42** [Rangi42/polishedcrystal#419]
![image](https://user-images.githubusercontent.com/35663410/76994030-2cd33600-6924-11ea-8e3e-7f8e6fb65498.png)

This will need fixing in the tutorial as well: https://github.com/pret/pokecrystal/wiki/Show-an-icon-for-the-current-weather

**Comment by FredrIQ** [comment]
Polished refactors the main battle loop somewhat, which is what caused this, so I'm not sure if this applies for tutorials. Either way, it's fixed in Polished now.
