### ISSUE TITLE
Goldenrod Radio Tower Team Rocket event may not deactivate

### ISSUE THREAD

**Issue by Rangi42** [Rangi42/polishedcrystal#420]
ETERNAL VlademirMujiK: This sequence of events fails to clear `ENGINE_ROCKETS_IN_RADIO_TOWER`:

1. Beat Team Rocket in Mahogany Town with Lance
2. Beat Pryce
3. Go to Blackthorn City
4. Go to the Radio Tower and beat Team Rocket
5. Beat Clair

**Comment by Rangi42** [comment]
Same issue as #397, which apparently wasn't fixed after all.

**Comment by itsdarsh** [comment]
Tested this out for myself and did a pretty thorough search for anything that may inappropriately set the flag or any way clearing the flag could be skipped. Nothing came up. Gonna go ahead and close this unless someone else reports it.
