### ISSUE TITLE
The player sprite can turn black in Azalea Pokémon Center

### ISSUE THREAD

**Issue by Rangi42** [Rangi42/polishedcrystal#421]
Polished S: "when you heal at Azalea after the Slowpoke Well event but before beating Bugsy"

![image](https://user-images.githubusercontent.com/35663410/77019622-89037d80-6957-11ea-9f7a-c4c26bdb7e77.png)

**Comment by Rangi42** [comment]
I can't reproduce this in BGB, even trying at different times of day, different plot points, and with `make hgss`.

**Comment by Rangi42** [comment]
Possibly related: Dare Evans: "After using the Pokemon center in Azalea for the first time, characters turn into letters during certain frames of their walking animation. Build da046593"

**Comment by FredrIQ** [comment]
From Discord reports, this happens only at a certain part of the Azalea event sequence. So perhaps trying to heal after each part of the Slowpoke Well quest, gym, etc, might reproduce this reliably.

**Comment by Rangi42** [comment]
I was able to reproduce this after Kurt made an Apricorn Ball.

![image](https://user-images.githubusercontent.com/35663410/79680665-17318480-81e0-11ea-821f-7d1501bb9dae.png)
