### ISSUE TITLE
Evolve Graveler

### ISSUE THREAD

**Issue by dwg1109** [Rangi42/polishedcrystal#437]
Hi - Love the game so far! I am playing v2.2.0.gbc on mGBA. I have a level 28 Graveler with 83 defense that I've EV trained defense on kakunas and metapods in Ilex forest to get it to evolve into a Golem, which it should need 50 EVs in defense according to the FAQ. I also EV trained it when it was a geodude on other geodudes in the cave that Falkner is in before the first gym. Based on some online sources I can verify that with 83 defense and brave nature, even if it had 31 IVs for defense I would have at least 75 EVs in defense. Have you had this problem before? Is it a problem if I EV trained it as a geodude before it evolved to a graveler?  Should I upgrade to the v3 beta?

**Comment by SadisticMystic** [comment]
Wild Geodude has a 21/1024 chance to be holding Everstone. Take off the held item.

**Comment by dwg1109** [comment]
Good idea, but the Graveler is holding a quick claw, no everstone. I got the Everstone from Bill's grandpa and sold it. The geodude didn't have an everstone when I caught it.

**Comment by SadisticMystic** [comment]
If the EV training was done after it reached level 28, it needs to consume another level-up to recheck the condition, so try again on the boundary to 29.

**Comment by dwg1109** [comment]
Just tried again, defense is up to 87 at level 29.

**Comment by dwg1109** [comment]
Another possibility is that the download I used wasn't actually v 2.2.0, I got the download from a non-github source... I wonder if I should download v3 and then try to open my save file on that one? Since it seems like the evolution method was only added at v2.2.0.

**Comment by dwg1109** [comment]
Update: I tried levelling up a geodude to Lv. 25 then EV training on metapod and kakuna to get >50 defense EVs, still didn't evolve.

**Comment by Rangi42** [comment]
Five Iron worth of Defense EVs are enough to make a Graveler evolve when it levels up:

![image](https://user-images.githubusercontent.com/35663410/77234422-ae290380-6b84-11ea-990f-2596bbf8615c.png)

**Comment by dwg1109** [comment]
I got it to evolve later. 

For the next bloke - I had tried to level up by EV training equivalent to 5 vitamins. However, GSC has stat exp (EVs didn't come round till gen 3), and vitamins are somewhat more powerful in gen 2 compared to battling wild kakunas and geodudes. So if you're trying to evolve off of wild pokemon you'll need about twice as many as you think you do.
