### ISSUE TITLE
Status conditions may coexist

### ISSUE THREAD

**Issue by Rangi42** [Rangi42/polishedcrystal#438]
![image](https://user-images.githubusercontent.com/35663410/77214544-12e15100-6ae6-11ea-93fc-70e1f65cb113.png)

ETERNAL VlademirMujiK: "Poisoned and burned at the same time and recovering life with Poison Heal. Toxic Orb poisoned me, Fire Punch burned me and Poison Heal was working either. Next match still burned, Poison Heal not working and half my attack because of the burn."

**Comment by itsdarsh** [comment]
Going through the discord logs, according to ETERNAL VlademirMujiK the order this happened in is Toxic Orb activation -> burn through Fire Punch. That order seems to work fine, `BattleCommand_burntarget` correctly checks for if the target is already statused (Toxic Orb sets `wBattleMonStatus` to `$88`.) However, the problems I'm having are when Fire Punch burns *before* Toxic Orb activates. `wBattleMonStatus` is properly set to `$10` so it's not an issue of two statuses at once, but Poison Heal still recovers health. This is fixed next battle.

**Comment by itsdarsh** [comment]
Even though I couldn't replicate this exactly I'll leave it closed because it _should_ be working now. If it pops up again I'll just reopen this.
