### ISSUE TITLE
Farfetch’d and Ampharos

### ISSUE THREAD

**Issue by nimbusquill** [Rangi42/polishedcrystal#444]
I am playing the version with the Pokémon type changes. Farfetch’d did not learn Karate Chop at level 21 like it is listed under its moves. It learned Twister. 

Upon evolution, Ampharos did not gain the dragon typing like it said in the files. Also, Flaaffy learned Take Down and Heal Bell at opposite levels.

**Comment by Rangi42** [comment]
Sounds like you're playing an old version.

**Comment by nimbusquill** [comment]
Thank you for the reply! I am playing version 2.2.0. Is this the most current?

**Comment by Rangi42** [comment]
No, 3.0 beta is the most current. The nightly release is updated automatically after every code commit.

**Comment by nimbusquill** [comment]
Oh, okay! I did not see that. I’m sorry for the confusion! Thank you!
