### ISSUE TITLE
rtc patch not working

### ISSUE THREAD

**Issue by NightFury135269** [Rangi42/polishedcrystal#450]
I found a rtc patch by infinest on romhacking.net but its breaks the rom but works fine with original rom. 
Please tell a fix or any other patch. 
Link to the rtc patch : https://www.romhacking.net/hacks/3841/

**Comment by NightFury135269** [comment]
I like your work a lot ,thanks for doing a great job. Keep it up.👍👍👍

**Comment by Rangi42** [comment]
That patch is for original Crystal, not Polished Crystal. It's not an issue with Polished Crystal.

Follow the INSTALL.md instructions to `make nortc`.
