### ISSUE TITLE
Quick Nurse Joy

### ISSUE THREAD

**Issue by NightFury135269** [Rangi42/polishedcrystal#451]
Add a option in menu for quick nurse joy which will make nurse joy just ask for yes/no for healing other than saying good morning or else which consume a lot of time and is boring hearing same thing everytime.

**Comment by NightFury135269** [comment]
I have few more ideas to tell is there any other way to discuss them. 
Thanks in advance.

**Comment by Rangi42** [comment]
You already earn this option by getting trainer card stars.
