### ISSUE TITLE
A new item binocular

### ISSUE THREAD

**Issue by NightFury135269** [Rangi42/polishedcrystal#452]
A binocular is an key item which can be used to look few distance ahead or back or side standing at a single place. It will be usefull to explore secret locations. 
Thanks in advance.

**Comment by NightFury135269** [comment]
This a new idea i thought of.

**Comment by Rangi42** [comment]
Please don't open issues unless they're actual issues with Polished Crystal (bugs with a recent 3.0 beta). Suggestions are welcome on the Discord server, the Pokécommunity forum post, etc.
