### ISSUE TITLE
Implement variant Alolan and Galarian forms

### ISSUE THREAD

**Issue by Rangi42** [Rangi42/polishedcrystal#453]
Animated front sprites and good back sprites:

- [x] Alolan Rattata
- [x] Alolan Raticate
- [x] Alolan Sandshrew
- [x] Alolan Sandslash
- [x] Alolan Vulpix
- [x] Alolan Ninetales
- [x] Alolan Diglett
- [x] Alolan Dugtrio
- [x] Alolan Meowth
- [x] Alolan Persian
- [x] Alolan Geodude
- [x] Alolan Graveler
- [x] Alolan Golem
- [x] Alolan Grimer
- [x] Alolan Muk
- [x] Alolan Raichu
- [x] Alolan Exeggutor
- [x] Alolan Marowak
- [x] Galarian Ponyta
- [x] Galarian Rapidash
- [x] Galarian Slowpoke
- [x] Galarian Slowbro
- [x] Galarian Slowking
- [x] Galarian Weezing
- [x] Galarian Articuno
- [x] Galarian Zapdos
- [x] Galarian Moltres

Party menu icons:

- [ ] Alolan Rattata
- [ ] Alolan Raticate
- [ ] Alolan Sandshrew
- [ ] Alolan Sandslash
- [ ] Alolan Vulpix
- [ ] Alolan Ninetales
- [ ] Alolan Diglett
- [ ] Alolan Dugtrio
- [ ] Alolan Meowth
- [ ] Alolan Persian
- [ ] Alolan Geodude
- [ ] Alolan Graveler
- [ ] Alolan Golem
- [ ] Alolan Grimer
- [x] Alolan Muk
- [ ] Alolan Raichu
- [x] Alolan Exeggutor
- [ ] Alolan Marowak
- [ ] Galarian Ponyta
- [ ] Galarian Rapidash
- [ ] Galarian Slowpoke
- [ ] Galarian Slowbro
- [ ] Galarian Slowking
- [ ] Galarian Weezing
- [ ] Galarian Articuno
- [ ] Galarian Zapdos
- [ ] Galarian Moltres

Wild locations (see `GenerateWildForm`):

- [x] Alolan Rattata
- [x] Alolan Raticate
- [x] Alolan Sandshrew
- [x] Alolan Sandslash
- [x] Alolan Vulpix
- [x] Alolan Ninetales
- [x] Alolan Diglett
- [x] Alolan Dugtrio
- [x] Alolan Meowth
- [x] Alolan Persian
- [x] Alolan Geodude
- [x] Alolan Graveler
- [x] Alolan Golem
- [x] Alolan Grimer
- [x] Alolan Muk
- [ ] Alolan Raichu
- [x] Alolan Exeggutor
- [ ] Alolan Marowak
- [x] Galarian Ponyta
- [x] Galarian Rapidash
- [x] Galarian Slowpoke
- [ ] Galarian Slowbro
- [ ] Galarian Slowking
- [ ] Galarian Weezing
- [ ] Galarian Articuno
- [ ] Galarian Zapdos
- [ ] Galarian Moltres

**Comment by Rangi42** [comment]
It doesn't really matter whether to use the `GetVariant` function or a raw Form value with `and FORM_MASK`. `GetVariant` only differs for Pikachu and Mewtwo; Mewtwo will later be changed to use a standard Form value, and Pikachu only differs in its sprite animation, like Unown or Magikarp. So `GetBaseData` can use whichever source of a form value is more convenient.

**Comment by Rangi42** [comment]
The one remaining `call GetBaseData` in `TryAddMonToParty`/`GeneratePartyMonStats` is needed for a lot of cases: new wild Pokémon, reloaded roaming Pokémon, trainers with hard-coded personality/DV/EV/etc values, gift Pokemon, etc. There's also duplicated code between it and `DayCare_InitBreeding`, since new Eggs and new wilds have similar initialization.

**Comment by Rangi42** [comment]
Regarding `TryAddMonToParty`, these are the cases:

- Generate a new Pokémon: set the appropriate form (based on location, time of day, etc) to `[wCurForm]`, then `call GetBaseData`, then use the value from `[wCurForm]` when initializing `wDVAndPersonalityBuffer`
- Load a roaming Pokémon: load its form from `wRoamMon#Form & FORM_MASK` to `[wCurForm]`, then `call GetBaseData`, then (as is done already) use the value from `wRoamMon#Form` when initializing `wDVAndPersonalityBuffer`
- Load a trainer Pokémon: load the right one's form from the party if one is specified, else default to form 1; this is only needed for `FillMoves`, since trainers with non-default forms will recalculate their stats after `ReadTrainerParty`

**Comment by Rangi42** [comment]
Call graphcs:

- `StartBattle` → `BattleIntro` → `InitEnemy` → `InitEnemyTrainer` → `ReadTrainerParty` → `TryAddMonToParty`
- `StartBattle` → `BattleIntro` → `InitEnemy` → `InitEnemyWildmon` → `LoadEnemyMon`
- `GivePoke` → `TryAddMonToParty`; if that fails, `GivePoke` → `LoadEnemyMon` to deposit in PC

**Comment by Rangi42** [comment]
Wild locations for Alolan/Galarian forms (see issue #453):

- [ ] Rattata/Raticate: location (Violet Outskirts? Murky Swamp?)
- [x] Sandshrew/Sandslash: Ice Path, Ice Island
- [ ] Vulpix/Ninetales: Seafoam Islands, Ice Island
- [ ] Diglett/Dugtrio: Cinnabar Volcano, Fire Island
- [ ] Meowth/Persian: location (Celadon Outskirts?)
- [ ] Geodude/Graveler/Golem: Magnet Tunnel, Rock Tunnel, Lightning Island
- [ ] Grimer/Muk: location (Shamouti Shrine Ruins?)
- [x] Raichu: evolve with Odd Souvenir
- [ ] Exeggutor: Shamouti, evolve with Odd Souvenir
- [ ] Marowak: Shamouti, evolve with Odd Souvenir
- [ ] Ponyta/Rapidash: Valencia Island
- [ ] Weezing: trade with a Galarian Sightseer

**Comment by FredrIQ** [comment]
#738 adds a bunch of unavailable regional formes as wild encounters. I checked those off in the list above.

**Comment by itsdarsh** [comment]
As far as I can tell, all graphics have been implemented. Placing them in-game, however, have not been fully implemented, so I'll leave #738 open.
