### ISSUE TITLE
Clear Body does not prevent Accuracy reduction

### ISSUE THREAD

**Issue by Rangi42** [Rangi42/polishedcrystal#458]
dwd: "Clear Body seems to be bugged, Mud-Slap lowers accuracy of my Clear Body Tentacool. Wild Sandshrew in Union Cave just used Mud-Slap on my Clear Body Tentacool, and it said it's super effective & Tentacool's Accuracy fell!"

**Comment by flempa316** [comment]
Looked at this, believe I have a fix. FYI Put clear body on pidgey so that I didnt have to hunt a clear body tentacool to test.
![fix for clear body](https://user-images.githubusercontent.com/58637645/78053447-9dc81400-734e-11ea-866b-73c74c79be6b.gif)

**Comment by FredrIQ** [comment]
Fixed
