### ISSUE TITLE
Hatching Eggs may glitch overworld sprites

### ISSUE THREAD

**Issue by Rangi42** [Rangi42/polishedcrystal#461]
Dare Evans: "Seems to be something to do with Togepi hatching. The last few times have been in Slowpoke Well, but I don't think that matters."

![image](https://user-images.githubusercontent.com/35663410/78256483-94fa4e00-74c6-11ea-964f-38bfc6fe6bfc.png)

flempa: "I know that that was happening in my own hack when I didn't properly use the setscene macro. ... So what I had done that caused the issue was used setmapscene to set the scene index to a value higher than there were scene scripts on the other map."

![image](https://user-images.githubusercontent.com/35663410/78256549-ae02ff00-74c6-11ea-8abf-0efd84acf7ae.png)

Cardshark000: "I got the post-togepi-hatching sprite bug too, though it ended up replacing my sprite and those of npcs with the sprites of the pokemon in my party and/or the hold-item icons. My personal sprite changes to match my party lead, while the npc sprites don't change. It started immediately after I nicknamed my togepi. I'm playing the 3/28/20 nightly build on the "My Oldboy! Free" android emulator."

![image](https://user-images.githubusercontent.com/35663410/78256619-c7a44680-74c6-11ea-88ea-afd2be4d027c.png)

![image](https://user-images.githubusercontent.com/35663410/78256646-d1c64500-74c6-11ea-8897-57fe26e7802c.png)

**Comment by flempa316** [comment]
![Sprite glitch](https://user-images.githubusercontent.com/58637645/78383557-9c912400-75a6-11ea-8479-fa01bcf2805d.gif)
Can replicate this super consistently when hatching the shiny from the daycare lady

**Comment by flempa316** [comment]
Apricots said in bugs:
"Ah i see
Giving a nickname may cause the sprites to get messed up.
Yep giving a nickname to the togepi caused the glitch
Giving this togepi a nickname is like catching MissingNo."
