### ISSUE TITLE
Catching Geodude before registering it in the Dex crashes

### ISSUE THREAD

**Issue by ExpoSeed** [Rangi42/polishedcrystal#470]
Attempting to catch Geodude will cause a crash when transitioning away from the battle screen.

If Geodude is registered in the Pokedex before attempting to catch it (only possible via WT except for debug), the game will not crash.

This issue does not exist with Pidgey, Sentret, Caterpie, Jigglypuff, or Sunkern

![image](https://user-images.githubusercontent.com/35663410/78822941-e2d0f380-79a9-11ea-88f3-82f849e268f9.png)

**Comment by ExpoSeed** [comment]
Dare Evans: "I've also got a crash. Caught Rattata, first catch of the save, went to a black screen. Build cf56e3b3"

possibly related. Both Geodude and Rattata are Pokemon with Alolan forms

**Comment by Rangi42** [comment]
Fixed in f67b29b8554d4c129dd50cd708cf42a8fc37721f.
