### ISSUE TITLE
The player's back sprite can be discolored during the foe's stat animation

### ISSUE THREAD

**Issue by Rangi42** [Rangi42/polishedcrystal#477]
J. Alex, aka The Huntress: "Build dated April 8th, 2020 (commit 7cfe2d24). This "discoloration" happens during the stat-up animation."

![image](https://user-images.githubusercontent.com/35663410/79031620-093f8c00-7b6e-11ea-8199-e8389cbc4bf7.png)

This may only be for X Items.

**Comment by flempa316** [comment]
I'll look at this later, don't think it's too hard to fix

**Comment by flempa316** [comment]
actually, I can't even reproduce this, fighting the same exact marowak, using the same X Speed (pokemaniac andrew union cave b1f) as pictured above.

**Comment by FredrIQ** [comment]
This is a result of closing the move screen not updating the attribute data, causing any further refreshes to it to sometimes mess up palettes for your Pokémon. This was fixed as part of ability slideout (which also ran into this problem), and thus fixing this as a side effect.
