### ISSUE TITLE
White screen after nicknaming a shiny Pokémon?

### ISSUE THREAD

**Issue by Rangi42** [Rangi42/polishedcrystal#479]
Dare Evans: "Just caught a shiny Weedle in Ilex Forest and got a white screen after the nickname screen. Was able to get out of it thankfully but it was scary. Build 9c873289"

**Comment by Rangi42** [comment]
I'm hoping 9ba024a2f86fbc787e503591bc57179d2891319d fixed this along with #461.

**Comment by FredrIQ** [comment]
Id did not, but this issue has already been fixed earlier. It was caused by overworld Pickup printing a message after the game had faded out all palettes to white. It was fixed as part of ability slideout implementation.
