### ISSUE TITLE
Some move animations are displaced when used by the foe

### ISSUE THREAD

**Issue by Rangi42** [Rangi42/polishedcrystal#480]
J. Alex, aka The Huntress: "I'm talking about the Facade animation." https://cdn.discordapp.com/attachments/332698384987193354/698188392319418429/20200410_100900.mp4

Ted95On: "Same thing happens with DazzlinGleam. The stars animation is played at the bottom on my text."

**Comment by Rangi42** [comment]
Rock Blast is another example.

**Comment by flempa316** [comment]
got a fix for dazzling gleam:
![anim](https://user-images.githubusercontent.com/58637645/79397747-da9a2a80-7f4c-11ea-83b5-e52c665a6bb3.gif)
and for rockblast:
![rckblst](https://user-images.githubusercontent.com/58637645/79398043-a83cfd00-7f4d-11ea-902e-5dbf47e9919c.gif)

**Comment by flempa316** [comment]
facade is significantly more complex unfortunately. can explain on the disc server

**Comment by flempa316** [comment]
trick room fixed:
![anim](https://user-images.githubusercontent.com/58637645/79475864-407ec480-7fd6-11ea-9eb5-d5d584b78bda.gif)
