### ISSUE TITLE
AI uses Hypnosis even though Insomnia prevents it

### ISSUE THREAD

**Issue by Rangi42** [Rangi42/polishedcrystal#481]
[Durand](https://www.pokecommunity.com/showpost.php?p=10145507&postcount=2414): "When using Ariados against Morty's ghost types, they continually use hypnosis against ariados, despite the fact that Insomnia Ariados is immune to it. They do this constantly and don't use any other moves, allowing Ariados to slowly and easily pick them off. I can only assume that this is because the AI is trying to use Dream Eater (as it is super effective) and is not properly registering Insomnia."

**Comment by Rangi42** [comment]
Morty already had the `AI_STATUS` flag; does it now understand Insomnia/Dream Eater?

**Comment by FredrIQ** [comment]
In theory it should have already, apparently on top of the existing problems with trainer classes, AI_Status was outright broken. This is fixed in 063178f.
