### ISSUE TITLE
AI ignores type chart

### ISSUE THREAD

**Issue by Rangi42** [Rangi42/polishedcrystal#482]
[Durand](https://www.pokecommunity.com/showpost.php?p=10145507&postcount=2414): "Many of the hiker's geodudes in the lower dark cave levels will continually use ground moves like magnitude and bulldoze on my Farfetch'd."
"The three not-so-secret sisters south of Goldenrod have a Staryu. The Staryu used Gyro Ball on my Farfetch'd multiple times instead of a water type move that would likely do more damage. The difference in speed between my farfetch'd and the staryu was probably not all that high, judging from the abysmal damage, so it really shouldn't be prioritizing that move."

Ted95On: "Also had a Pokemon spamming Normal moves on my Mismagius, can’t remember which though."

(Some of these may be expected for trainer classes with poor AI, but Gym Leaders use smart enough AI that these shouldn't happen.)

**Comment by FredrIQ** [comment]
IMO any AI (besides perhaps route 29 ones) should at least avoid using completely ineffective moves.

**Comment by Rangi42** [comment]
If badges > 2, `or` the AI with basic flags; if > 8, `or` with intermediate flags; if > 16, `or` with advanced flags.

**Comment by FredrIQ** [comment]
Fixed in 5379006.
