### ISSUE TITLE
Pokémon with forms have glitched sprites upon capture

### ISSUE THREAD

**Issue by Rangi42** [Rangi42/polishedcrystal#483]
[Durand](https://www.pokecommunity.com/showpost.php?p=10145698&postcount=2416): "Just caught a Pikachu in the Yellow Forest, and on the new entry pokedex screen right after the battle, the sprite is all chopped up into different pieces."

**Comment by itsdarsh** [comment]
Not able to replicate this personally, at least as written above, but maybe someone else has.

**Comment by Rangi42** [comment]
Polished S: "Regular form Geodude's evolutions to Graveler and Golem are still bugged as of the latest commit, 2250d7d3. The sprites glitch for a minute or so before the evolution completes; luckily, it doesn't crash the game, but it's still annoying. The Alolan Formes don't have this issue."

![image](https://user-images.githubusercontent.com/35663410/79883616-23753780-83c2-11ea-9233-cff6302f85a8.png)

**Comment by Rangi42** [comment]
roytam1: "got this when I brick breaking in Tohjo Falls"

![image](https://user-images.githubusercontent.com/35663410/79883828-5dded480-83c2-11ea-9198-3f0561beacc4.png)

![image](https://user-images.githubusercontent.com/35663410/79883786-53bcd600-83c2-11ea-94fa-4fc6b7810d70.png)

bloodless: "Geo is 40x40 ponyta is 48x48 so yeah the screwed part is dimensions. It's clearly calling the wrong sprite (the next evo form line in the list) but not consistently since the other one has a normal sprite"

**Comment by itsdarsh** [comment]
Should be fixed by 7d29687

**Comment by roytam1** [comment]
> Should be fixed by [7d29687](https://github.com/Rangi42/polishedcrystal/commit/7d29687f68b4922ac2c8846ee1a8a7f2dd20fa59)

not for my case.
![image](https://user-images.githubusercontent.com/1192577/80233745-8fd58c80-8689-11ea-9fcb-7f016bc48574.png)
