### ISSUE TITLE
Roost Animation Crashes Game

### ISSUE THREAD

**Issue by XModxGodX** [Rangi42/polishedcrystal#490]
When fighting Falkner and his Pidgeotto uses Roost in the latest build of the game the animation leads to this screen:
![polishedcrystal-3 0 0-beta 1](https://user-images.githubusercontent.com/22751086/79508413-61ebaa80-7fee-11ea-9308-b78329f0fe4e.png)

**Comment by FredrIQ** [comment]
Cannot reproduce this. Which emulator do you use? VBA is very prone to crashing during battles and is not recommended, in case you use that one.

**Comment by XModxGodX** [comment]
I used the Wii port of it VBA GX.

**Comment by FredrIQ** [comment]
Try using gambatte. BGB is windows-only (kinda), but gambatte has been ported to a lot of systems, possibly including Wii.
