### ISSUE TITLE
Add a Moves option to PC's Withdraw/Deposit menus

### ISSUE THREAD

**Issue by roytam1** [Rangi42/polishedcrystal#492]
It would be nice to show move types in status page as gen4 games do so.

**Comment by FredrIQ** [comment]
The way the summary screen is designed makes this a bit awkward. What Polished Crystal has done however is to improve the Move interface (also accessible from the party menu), which lists type, category, power, accuracy.

**Comment by roytam1** [comment]
> improved the Move interface

This is a nice move, but it does not solve the problem when managing pokemons in boxes.

**Comment by Rangi42** [comment]
Mockup:

![image](https://user-images.githubusercontent.com/35663410/79626962-643f2900-8102-11ea-920c-f947f07491f8.png)

**Comment by roytam1** [comment]
thats good, if left/right arrow works with prev/next pokemon in box.

**Comment by roytam1** [comment]
> Mockup:
what about move menu?
![move](https://user-images.githubusercontent.com/1192577/79628138-f716ac80-8170-11ea-9129-c5d8e014cf95.png)

**Comment by FredrIQ** [comment]
Perhaps rename to Switch (same as in party menu) to avoid the ambiguity.

**Comment by roytam1** [comment]
> Perhaps rename to Switch (same as in party menu) to avoid the ambiguity.

but it does mean "Move" pokemon between box(es) and/or party. Renaming it to "Switch" may not have same meaning.

**Comment by Rangi42** [comment]
Gen VI renamed "Move Pokémon" to "Organize Boxes", and I've always found the "w/o Mail" qualifier distracting. So "Move PKMN w/o Mail" could be "Organize Boxes", and individual "Move" could be "Organize" (or "Swap", "Shift", "Place", "Sort", etc).

**Comment by roytam1** [comment]
> I've always found the "w/o Mail" qualifier distracting

but pokemon having mail can't be moved from party to box.

**Comment by FredrIQ** [comment]
Thing is, that is also the case for Withdraw and Deposit, which has no such denominator. Also, this restriction also applied to 3gen and 4gen, which do not have the "w/o Mail" addition to the storage system menu.

**Comment by FredrIQ** [comment]
This issue is now redundant with #510. This is to be done as part of that UI rework
