### ISSUE TITLE
Game freezes when encountering Kangaskhan with Parental Bond

### ISSUE THREAD

**Issue by itsdarsh** [Rangi42/polishedcrystal#497]
Occurred when roytam1 and a nice Pidgeot encountered a Lv60 Kangaskhan in the Safari Zone.

![](https://cdn.discordapp.com/attachments/332698384987193354/702407639208034344/kangaskhan.png)

**Comment by itsdarsh** [comment]
Not able to replicate this yet, I'll update if I get more info.

**Comment by itsdarsh** [comment]
From roytam1:
>> @roytam1 can you give me more information about the game crashing with encountering kangaskhan? I can't replicate this

>@darsh with latest nightly it seems to be fixed, tested with bgb and my vba fork.

I'll leave this open but there's probably no harm if this is closed.

**Comment by the-s-is-silent** [comment]
It's Parental Bond that's causing the crashes. Bug is still present as of the most recent commit.

**Comment by FredrIQ** [comment]
This was fixed somewhat recently. Incidentally, it actually had nothing to do with Parental Bond, but rather an invalid "special move".
