### ISSUE TITLE
Continuing save results in "Pokemon Learned !" message looping until game crashes

### ISSUE THREAD

**Issue by THTB614** [Rangi42/polishedcrystal#512]
Not exactly sure what action triggered this, but after attempting to load a save file, I was stuck in a loop of the above message in quotes until the game crashed, rendering the save file unusable.

Actions taken leading up until issue:
-Caught Ledyba (Pokemon whose name was used)
-Ledyba was in 1st slot in party
-Saved in front of Cool Trainer that gives you Air Balloon
-Restarted game during battle

**Comment by FredrIQ** [comment]
Did you load a save from an old version?

**Comment by THTB614** [comment]
Sorry for late response.

The emulator I use (Gambatte core for RetroArch) didn't recognize my save data from a previous version, so I assumed I was okay.  Probably should have deleted that one first.  I'll try doing that.

**Comment by THTB614** [comment]
Reporting back.

This seems to have corrected the issue.  Sorry about that!
