### ISSUE TITLE
Interaction between forms, Transform, and capture

### ISSUE THREAD

**Issue by Rangi42** [Rangi42/polishedcrystal#518]
ImSleepAf: "ditto transformed into my alolan sandshrew then i threw a ball. when it popped out it was a regular sandshrew"

**Comment by FredrIQ** [comment]
Probably just a visual bug but I'll look into it

**Comment by Rangi42** [comment]
Even just entering and exiting the Bag is enough to reset the Ditto's form.

![image](https://user-images.githubusercontent.com/35663410/89220818-3b06b380-d5a0-11ea-92a2-75dcf0c8cb35.png)
