### ISSUE TITLE
Stack underflow crash upon continuing game

### ISSUE THREAD

**Issue by frezgle** [Rangi42/polishedcrystal#522]
Continuing from a saved game glitches the screen and ends on this error:
![Capture](https://user-images.githubusercontent.com/30140927/83360503-c3be6480-a34f-11ea-8bb0-fb7e0e4cddcc.PNG)
On the latest build (e424206), using BGB. I had just gotten HM02 and was in Nuzlocke Mode, if that helps. Don't remember what specific area/route I had saved in though.

**Comment by FredrIQ** [comment]
Did you update the game?

**Comment by frezgle** [comment]
Nope, file was started on the same build.

**Comment by FredrIQ** [comment]
Fixed recently, games didn't correctly write the save version field upon saving, and thus it was filled with garbage in corner cases.
