### ISSUE TITLE
Some contact moves are missing

### ISSUE THREAD

**Issue by earthoul** [Rangi42/polishedcrystal#527]
From the source code:

Some contact moves are missing in `ContactMoves` below: Acrobatics, Aqua Jet, Avalanche, Brave Bird, Double Slap, Facade, Struggle, & Sucker Punch.
https://github.com/Rangi42/polishedcrystal/blob/1d8419c7d6c2ecb6f2ac40b1877798baa1052b6b/engine/battle/misc.asm#L17-L102

**Comment by FredrIQ** [comment]
Struggle is checked seperately because it's move 255, which the usual list functions treat as "end of list". Good point about the rest
