### ISSUE TITLE
Ecruteak Dance Theatre Gentleman lacks a period or w/e at the end of his words

### ISSUE THREAD

**Issue by earthoul** [Rangi42/polishedcrystal#528]
From the source code:

One of the lines of the gentleman at Ecruteak Dance Theatre doesn't have a period, an ellipsis or whatever at the end:

https://github.com/Rangi42/polishedcrystal/blob/a4114d887cb52d8242cb720fc6877138158a8bfb/maps/DanceTheatre.asm#L218-L222

**Comment by FredrIQ** [comment]
Fixed by #530.
