### ISSUE TITLE
Proposal to implement Move/Swap Items menu option

### ISSUE THREAD

**Issue by FranktheMute** [Rangi42/polishedcrystal#534]
Proposal to include a Move/Swap button on the 'Item' sub-menu of the pokémon party screen for easier item moving. The feature has been in the core games since gen 4 or 5 and is an important piece of QoL that is sorely missed.

User Captain Kennedy on the discord says, "Prism added a swap option for items in the party screen. Also works if one pokemon has an item but the other doesn't.", so maybe this piece of code could be ported or something, I don't know. I'm not a coding cybergenius like you guys.

**Comment by Rangi42** [comment]
Yeah, Item → Give/Take/Swap would make sense.
