### ISSUE TITLE
Breeders issue 

### ISSUE THREAD

**Issue by JaydeMay** [Rangi42/polishedcrystal#538]
They did not re battle like on 2.2 Don’t know if this is a bug or intentional

**Comment by itsdarsh** [comment]
This is intentional, because people kept assuming that was a bug (it's not, Gen 5 breeders also rebattle... but they no longer battle in this game regardless.)

**Comment by JaydeMay** [comment]
Ah what a shame was good for exp. and money!! I knew it was the same as gen 5 and thought it was a nice touch!

**Comment by itsdarsh** [comment]
Me too! But too many people got confused :(
