### ISSUE TITLE
Blaine-rematch's Magcargo has a bizzarre moveset with an impossible move

### ISSUE THREAD

**Issue by earthoul** [Rangi42/polishedcrystal#541]
From the source code:

https://github.com/Rangi42/polishedcrystal/blob/337f03b1035c10060b098e5b732bf517f4a17546/data/trainers/parties.asm#L990-L995

Issues about this:

1. Magcargo can't learn Dragon Dance. (Neither in Gen 8 data.)
1. Since it's from Blaine's rematch team, it should have an optimized moveset. Currently, it looks physically & flinch-&-stall oriented with DD. Since DD is impossible & those strats aren't optimal for Magcargo, it should have its moveset renewed. (Possibly as a Shell Smash wallbreaker.)

Found by: `@Salamandar` in `#bugs`

**Comment by FredrIQ** [comment]
Fixed in f6342434e.
