### ISSUE TITLE
PP inaccuracy with PPmax item

### ISSUE THREAD

**Issue by Salamandar73** [Rangi42/polishedcrystal#549]
If you use PPmax on a 5PP attack, it goes to 6/8. It should not do the same when using PPup thrice.

**Comment by Rangi42** [comment]
This applies to all moves; current PP is only boosted once, even if the PP Max raised it by 2 or 3 PP Ups.

PP Ups should be refactored into their own byte anyway.

**Comment by FredrIQ** [comment]
Fixed in 090919a275f92f855a39eecb808e708fe831ad6e.
