### ISSUE TITLE
How to use IV color pallates?

### ISSUE THREAD

**Issue by mattmills49** [Rangi42/polishedcrystal#551]
How exactly would I use the "IV vary colors" option to identify stronger pokemon in the wild? Are they always a darker shade? For example I have one geodude with like a green shading and another that is more sand color, would I be able to tell just by looking which one is stronger? Just looking for some more specifics into how it works, thanks!

**Comment by Salamandar73** [comment]
I can't help you about the RGB details, but for in-game piratical play through, I can give you some tips.
- DV value 0-15 in GSC, but same behavior as IV have influence on the Pokemon color variation but not on shininess, another test is perform for that (1/4096, 3/4096 late game). By experience, the more neutral it looks, the most balanced are the stats, either full bad or full good. Green rocks
- In version 3.0.0 (don't play the outdated 2.2.0), there is a judging machine in goldenrod that shows the DV and EV of the Pokemon you select. It is displays on an hexagone graph, with a start to tell the stat is perfect. To enable the machine, you need to breed and hatch an egg (not the odd-egg). 
- If you have enabled the perfect stats at the beginning of the game, Pokemon stats are considered perfect for dmg calculation but there are still color variations based on the DV. 
Don't hesitate to come to the discord for your questions, the server is pretty active.

**Comment by mattmills49** [comment]
Thanks for the reply and suggestions, I'll move my question to the discord server.
