### ISSUE TITLE
Graphical glitches and evolution color

### ISSUE THREAD

**Issue by Salamandar73** [Rangi42/polishedcrystal#560]
- [ ] #916
![Kan sprite](https://user-images.githubusercontent.com/68333818/89536523-5409a180-d7f8-11ea-85d3-be5d2491b2bd.gif)
- [x] A shiny surfing pikachu, change to a flying one sprite during the evolution. Then, the initially blue Alolan Raichu (very good looking) is still shiny but not blue anymore.
![A-Raichu Shiny](https://user-images.githubusercontent.com/68333818/89536639-81564f80-d7f8-11ea-8164-ba49aa5ea7b4.gif)
![polishedcrystal-3 0 0-beta-358](https://user-images.githubusercontent.com/68333818/89536650-87e4c700-d7f8-11ea-9fd4-0d93a44229e5.png)
![polishedcrystal-3 0 0-beta-359](https://user-images.githubusercontent.com/68333818/89536661-8b784e00-d7f8-11ea-8786-560bd778522e.png)
The problem doesn't appear with other alolan forms like Exeggutor
![A-Exeggutor Shiny](https://user-images.githubusercontent.com/68333818/89536798-b498de80-d7f8-11ea-84a8-8359997e6e47.gif)

**Comment by FredrIQ** [comment]
Fixed in 9bit in 9171eee.

**Comment by FredrIQ** [comment]
Hm, this issue has multiple parts to it. Reopening for this reason. Only evolutions were fixed.
