### ISSUE TITLE
Somehow clipped through right wall of starting room then crash with Error: 3

### ISSUE THREAD

**Issue by DasaniWaterB** [Rangi42/polishedcrystal#564]
![Screen Shot 2020-08-20 at 8 07 36 AM](https://user-images.githubusercontent.com/69925158/90684867-00e62300-e2bd-11ea-841b-d6494a0a8519.png) 
title says it all? If it helps it's the latest available beta version.

**Comment by Rangi42** [comment]
Fixed by 05d1bb636e86314647e72d3c2376c94897848df3 and e64387a2b3bfe3af042f66a3c2e9f27ab38a3d95.
