### ISSUE TITLE
Support variant forms for SPRITE_MON_ICON and pokemon_events

### ISSUE THREAD

**Issue by Rangi42** [Rangi42/polishedcrystal#565]
Variant forms already have their own icons, but they're not supported in the overworld.

`pokemon_event`s, and `object_event`s that use `SPRITE_MON_ICON`, store the icon species in the `object_event`'s X/Y walking radius byte. (`pokemon_event`s also store the species again in the sight range byte, as an argument to the `showcrytext` command for `OBJECTTYPE_POKEMON`.)

`GetMonSprite` reads the species from the `MAPOBJECT_RADIUS` offset, and assumes the form is 0. (`SPRITE_DAYCARE_MON_1` and `SPRITE_DAYCARE_MON_2` do use a stored form, so that's already possible.)

We could store the form value in the radius byte, and the species in the range byte. How this would apply:

- `pokemon_event`s and other `OBJECTTYPE_POKEMON` already store the species in their range for `showcrytext`
- `OBJECTTYPE_SCRIPT` stores an unused 0 in the range, so it's free
- There are a few (eight) `SPRITE_MON_ICON` with `OBJECTTYPE_COMMAND` that already use the range byte for `jumptext`, but these could become `OBJECTTYPE_SCRIPT`

Then `GetMonSprite` would have to read the `MAPOBJECT_RADIUS` offset for the form and `MAPOBJECT_RANGE` offset for the species. This is complicated by how `ReloadSpriteIndex` actually passes a pointer to part of an `object_struct` instead of a `map_object`, suitably adjusted by `OBJECT_RADIUS - MAPOBJECT_RADIUS`. However, `OBJECT_RANGE - MAPOBJECT_RANGE` ≠ `OBJECT_RADIUS - MAPOBJECT_RADIUS`, so this would need more careful handling, maybe just an HRAM flag.

**Comment by Rangi42** [comment]
Every `object_event` has its `clock_hour` byte as the nonfunctional `-1`; this could be repurposed for something. (Although `object_struct` does not have copies of `clock_hour` or `clock_daytime`.)

**Comment by itsdarsh** [comment]
This has been implemented in 9bit, so when that gets merged into master I'll close this.

**Comment by Rangi42** [comment]
Resolved in `9bit`.
