### ISSUE TITLE
engine/pokemon/search.asm needs refactoring to handle flags properly

### ISSUE THREAD

**Issue by earthoul** [Rangi42/polishedcrystal#567]
> `#questions`
>
> 2020-08-23 20:45 UTC
> Rangi: but I may just replace the whole logic with flags for when you catch \[legendaries\]
>
> 2020-08-23 20:53 UTC
> Rangi: \[…\] There are too many possible combinations of "triggered the event, seen the mon, caught the mon, still own the mon".  I'll bet this is responsible for \[#208\].

[search.asm](https://github.com/Rangi42/polishedcrystal/blob/feb69f82570f9b010ce77f931c63a8941035f3f4/engine/pokemon/search.asm) contains `SpecialBeastsCheck`, `SpecialBirdsCheck`, `SpecialDuoCheck` and more, which are also related to some flags such as Eusine and Lawrence. Some cases (not fully descriptive yet, though), including but not limited to #208, don't set those flags properly.

Found by: `@Salamandar`, `@singularity`, `@Rangi` & Co. on `#questions`

**Comment by Rangi42** [comment]
Related pokecrystal bug: https://github.com/pret/pokecrystal/blob/master/docs/bugs_and_glitches.md#checkownmonanywhere-does-not-check-the-day-care
