### ISSUE TITLE
Ruins of Alph crash

### ISSUE THREAD

**Issue by Styvoo9X** [Rangi42/polishedcrystal#568]
When i return to Ruins of Alph after all Unown are caught and Sinjoh Ruins is unlocked, to talk to the scientist in Kabuto puzzle room causes game crashes.

Version played : v3 beta

**Comment by FredrIQ** [comment]
Did you update the game before running into this crash? Game updates can cause script problems if you donkt leave an area after an update.

**Comment by FredrIQ** [comment]
Nobody else has reported this bug, and I got no response about whether or not this was caused by a game update. Closing for now unless more information can shed light on this and possibly confirm the bug.
