### ISSUE TITLE
Battle Tower overwrites the player's Pokémon's stats incorrectly

### ISSUE THREAD

**Issue by earthoul** [Rangi42/polishedcrystal#570]
Battle Tower incorrectly overwrites some stats of all the three Pokémon the player carries, just before the first battle begins after the player entered the battle room.

Before:
![bgb00029](https://user-images.githubusercontent.com/7924788/92746631-66aa6400-f3be-11ea-9788-18f26ed27a38.png) ![bgb00030](https://user-images.githubusercontent.com/7924788/92749151-cdc91800-f3c0-11ea-8b92-bc5a5d7d1a2a.png) ![bgb00031](https://user-images.githubusercontent.com/7924788/92749160-d02b7200-f3c0-11ea-8fd1-fb09a5f8dac2.png)

In-battle:
![bgb00032](https://user-images.githubusercontent.com/7924788/92746649-69a55480-f3be-11ea-8479-e53dcc6cac54.png) ![bgb00033](https://user-images.githubusercontent.com/7924788/92749171-d3bef900-f3c0-11ea-825d-e6bd24596413.png) ![bgb00034](https://user-images.githubusercontent.com/7924788/92749179-d6215300-f3c0-11ea-9735-46b760a14a1f.png)

The stats get back to normal when the player loses and goes back to the lobby.

In this case, DVs & EVs (all maxed) remained unchanged; `@idkyetmane` had another case where HP was also affected.

Here's a screenshot of BGB's debug mode when the game overwrote the Speed stat of the lead (A-Muk) from $66 (102) to $5B (91):
![breakpoint](https://user-images.githubusercontent.com/7924788/92747342-0e279680-f3bf-11ea-94b5-ef82df71b984.png)

Found by: `@idkyetmane`, `@Ted95On` & Co.; I've re-confirmed it on the debug build `polishedcrystal-3.0.0-beta-debug-cb2a2501`

**Comment by FredrIQ** [comment]
Fixed in 517de0f7aa4b3b1d02467f9cc427aa67411d4910.
