### ISSUE TITLE
Some TMs have wrong color palettes

### ISSUE THREAD

**Issue by earthoul** [Rangi42/polishedcrystal#571]
From the source code:

[The palette file](https://github.com/Rangi42/polishedcrystal/blob/5d992ffb3c5e1d68e3b8613ccfff1c869dbc1f08/engine/gfx/palettes.asm#L1212) has wrong attributes to some TMs:

- TM37 Sandstorm is Rock type;
- (TM42 Facade lacks a comment;)
- TM43 is now Flame Charge;
- TM57 is now Wild Charge;
- TM58 is now Dark Pulse;
- & TM68 Giga Impact is Normal.

Found in-game first by `@BryceTT` on TM57.

**Comment by FredrIQ** [comment]
Fixed in b562f8d.
