### ISSUE TITLE
Game crashes upon attempting to load save

### ISSUE THREAD

**Issue by gullwv** [Rangi42/polishedcrystal#575]
![image](https://user-images.githubusercontent.com/45007150/95661635-d6ffee80-0afe-11eb-873e-2c94a105e37e.png)
Playing on BGB, using `b2e493f` (the most recent nightly available from Releases).
Saved right in front of the Air Balloon-using Ace Trainer on Route 31 before challenging him. After soft-resetting during the battle, I attempted to continue only to run into error `000`.

**Comment by FredrIQ** [comment]
Should be fixed in b6c2c5a34a7e1c0baa2db111f92610230df83596.
