### ISSUE TITLE
Can't move at all?

### ISSUE THREAD

**Issue by dawnmew** [Rangi42/polishedcrystal#576]
I compiled the current master (676398432f23947ef98ff8743f60b4a7d1f01828), and at the very beginning of the game in the player's room, I can't move at all other than turning in place -- it's like the entire room has collision set to solid. I know masters aren't meant to be stable, but, uh...!

**Comment by dawnmew** [comment]
More info: Compiled fresh on Xubuntu 20.04.

**Comment by dawnmew** [comment]
Update: **The culprit is the latest version of rgbds.** Downgrading to 0.4.1 completely fixes the issue. Looks like there's an incompatibility to look into here!

**Comment by Rangi42** [comment]
0.4.1 *is* the latest version. 0.4.2 will be supported when it is released.
