### ISSUE TITLE
Unable to move at start. Stuck in the bedroom

### ISSUE THREAD

**Issue by LennyMacca** [Rangi42/polishedcrystal#588]
Started a game on the latest faithful build (7e67e77d) of the 3.0.0 release but my character can't move and I have been stuck in the bedroom.
![gambatte_qt_win32-r571_Glxg6hujs7](https://user-images.githubusercontent.com/45352979/101822052-5f305d80-3b5b-11eb-8c4f-0a4107a66f5f.png)
![gambatte_qt_win32-r571_HorHC9bfkf](https://user-images.githubusercontent.com/45352979/101822076-65bed500-3b5b-11eb-8e4e-fe251ad4e4f9.png)
![gambatte_qt_win32-r571_3xlx1qfZig](https://user-images.githubusercontent.com/45352979/101822090-6a838900-3b5b-11eb-99d7-1655cc2538d7.png)
As you can see, i can change my direction but can't walk. I was able to move just fine in the 2.2.0 version however

**Comment by FredrIQ** [comment]
Fixed in e0c5199c1bc36c86ad7b33c4adaa2eee66bfac61.
