### ISSUE TITLE
Rewrite how Battle Tower teams are chosen

### ISSUE THREAD

**Issue by Rangi42** [Rangi42/polishedcrystal#591]
There's now a single list of 306 teams in no particular order, instead of 10 sets of 21 mons each in roughly increasing power order. The code to load and store teams needs to be updated accordingly.

**Comment by Salamandar73** [comment]
The sets are ordered in 4 tiers (with terminator db -1)
(C)rap
(A)verage
(G)ood
(E)xcellent

Trainers should have points increasing, and pick a team with this table: 
8pts: EEG
7pts: EEA or EGG
6pts: EGA or GGG
5pts: EAA or GGA
4pts: GAA or GGC
3pts: GAC or AAA
2pts: GCC or AAC
1pts: ACC

No (E) and (C) sets together, and pokemon order in the party should be shuffled too.
Trainers start with 1 point, the first tycoon has 7 pts, then all have 8 points.

**Comment by Salamandar73** [comment]
[parties.txt](https://github.com/Rangi42/polishedcrystal/files/5882223/parties.txt)

**Comment by Salamandar73** [comment]
Update without tier (x) and stats comments
[parties.txt](https://github.com/Rangi42/polishedcrystal/files/5913086/parties.txt)

**Comment by Rangi42** [comment]
> Update without tier (x) and stats comments

That's already done; you can just update data/battle_tower/parties.asm if necessary.

**Comment by FredrIQ** [comment]
The improvements to Battle Tower during the last few days addresses this issue nicely.
