### ISSUE TITLE
Link softlock

### ISSUE THREAD

**Issue by FredrIQ** [Rangi42/polishedcrystal#595]
b069adaba broke link. This reproduces the problem:
* Player A starts the link session with the receptionist until the first "Please wait.".
* Player B starts the link session with the receptionist until the first "Please wait.".
* Player A saves the game and goes to the second "Please wait." dialog.
* Player B saves the game and goes to the second "Please wait." dialog.

This causes Player A to get stuck on the dialog forever while Player B gains access to the link room. Note that if the one who prompted the first "Please wait." dialog first, waits for the other player to prompt the second "Please wait." dialog first, the link is successful, hence why I noted steps on how to reproduce.

**Comment by itsdarsh** [comment]
`wcf57` (`wUnusedPlayerLinkAction` in vanilla) isn't actually unused.
