### ISSUE TITLE
Ninetales family + Shadow Ball inconsistencies

### ISSUE THREAD

**Issue by earthoul** [Rangi42/polishedcrystal#601]
Current state:

- Among the four members of the family, only Kantonian Ninetales is compatible with Shadow Ball TM (which is consistent with the MSGs)
- Polished has also added Shadow Ball as a level-up move for both Kantonian and Alolan Vulpix, enabling all the four to use the move in a bizarre manner 
- Those new level-up moves come with a comment `-> TM move`, though Vulpix isn't compatible with the TM 

It should be either:

- Remove Shadow Ball from both Vulpix, or
- Enable K-/A-Vulpix and A-Ninetales to learn Shadow Ball via TM (maybe along with `-> new move` rather than `-> TM move` in the comment?)

Found in-game first by `@ShadowAshuri` on `#questions`; reported by @Salamandar73 on `#bugs`

**Comment by FredrIQ** [comment]
All of the family now learns Shadow Ball by TM as of e9099702af1cc3c16f28d0b95f824941cee5001f.
