### ISSUE TITLE
Save patching issues please help

### ISSUE THREAD

**Issue by FieryMewtwo** [Rangi42/polishedcrystal#614]
I have tried to patch my 3.0.0 beta save with the Prism BPS Patcher at pokemonprism.com, but it says my save is corrupted. Can someone help me with this? Thanks!

**Comment by itsdarsh** [comment]
@FieryMewtwo How old is your save? Also, make sure you're using the save file and not a save state.

**Comment by FieryMewtwo** [comment]
It's from about a week ago. It's a .sav file

**Comment by FieryMewtwo** [comment]
I can send it here if neccessary

**Comment by FieryMewtwo** [comment]
@itsdarsh Hello?

**Comment by itsdarsh** [comment]
This would probably be easier done on discord, but please send the save file.

**Comment by FredrIQ** [comment]
Fixed after a talk on Discord. Turns out it was a flashcart being pelicular about things.

**Comment by FieryMewtwo** [comment]
Um, I'm not using a flash cart, but here
[polishedcrystal-saves.zip](https://github.com/Rangi42/polishedcrystal/files/6231228/polishedcrystal-saves.zip)

**Comment by FieryMewtwo** [comment]
I'm using a web-based GBC emulator.

taisel.github.io/GameBoy-Online/

**Comment by FieryMewtwo** [comment]
That could be part of the problem

**Comment by rofl0r** [comment]
for anyone else prefering bulk edits in a hex editor, here's a small C program that loads the battery save file (for 3.1.1) and calculates the correct checksum so one can get past the corruption check without having to hack the rom to disable the check (optimally the check would offer an option to load it anyway if the user knows what he's doing).
i used this to edit the count of items in meds bag successfully, but it's possible that editing mons has yet another checksum per mon from what i've gathered. if you only want to edit a single value than indeed it's simpler to just do it with the emulator's built-in cheat tool.

```c
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <assert.h>

uint16_t checksum(uint8_t *data, int start, int end) {
	uint16_t c = 0;
	int i = start;
	for(; i < end; ++i) c += data[i];
	return c;
}

uint8_t *load_file(char *fn) {
	FILE *f = fopen(fn, "r");
	if (!f) return 0;
	const int d_sz = 32*1024;
	uint8_t *data = malloc(d_sz);
	assert(fread(data, 1, d_sz, f) == d_sz);
	fclose(f);
	return data;
}

typedef struct symaddr { int bank; uint16_t addr; } symaddr;
uint32_t getsramsymaddr(const symaddr *sa) {
	return sa->bank * 0x2000 + sa->addr - 0xa000;
}

int main(int argc, char** argv) {
	// 4 sym values taken from polishedcrystal-3.1.1.sym
	const symaddr sGameData = {1, 0xa008};
	const symaddr sGameDataEnd = {1, 0xab83};
	const symaddr sBackupGameData = {0, 0xb208};
	const symaddr sBackupGameDataEnd = {0, 0xbd83};

	const int gd_start = getsramsymaddr(&sGameData);
	const int gd_end = getsramsymaddr(&sGameDataEnd);

	// currently hardcoded
	// 00002D00   FF FF FF FF  FF FF FF FF  FF FF FF FF  FF B3 56 7F  ..............V.
	//                                                      xx xx
	// calculated checksum is 0x56b3

	const int checksum_loc = 0x2d0d;

	const int backup_checksum_loc = 0x1f0d;

	uint8_t *data = load_file(argv[1]);
	uint16_t chksum = checksum(data, gd_start, gd_end);
	uint16_t file_checksum = data[checksum_loc+0] | (data[checksum_loc+1] << 8);

	printf("file checksum (offset %08x): %04x, calculated checksum: %04x\n",
		checksum_loc, file_checksum, chksum);
	printf("checksum %s\n", file_checksum == chksum ? " matches" : " mismatches");
	printf("note that the checksum in file is little endian so the bytes need to be swapped\n");
	return file_checksum != chksum;
}
```

usage: `gcc polished-save.c -o polished-save && ./polished-save polishedcrystal-3.1.1.srm`
output looks like

```
file checksum (offset 00002d0d): 56b3, calculated checksum: 5ffc
checksum  mismatches
note that the checksum in file is little endian so the bytes need to be swapped
```

in case of the above mismatch, open the sav/srm file in the hexeditor and change "b356" to "fc5f" at offset 0x2d0d. after that polishedcrystal should accept it.
