### ISSUE TITLE
Cianwood city move relearner

### ISSUE THREAD

**Issue by Turdfergason67** [Rangi42/polishedcrystal#618]
Some Pokémon cannot use the move relearner. The message "is not compatible with (Pokémon) it cant learn." pops up. Occasionally a move title or Pokémon nickname begins the message. 
![glitch](https://user-images.githubusercontent.com/82064673/113790475-4b0a0080-96f6-11eb-97a7-83b6f56ef258.png)
![glitch2](https://user-images.githubusercontent.com/82064673/113790478-4ba29700-96f6-11eb-88a4-c08a691874f5.png)
![glitch3](https://user-images.githubusercontent.com/82064673/113790481-4ba29700-96f6-11eb-9848-96219829b4c8.png)

**Comment by itsdarsh** [comment]
Fixed in 9bit
