### ISSUE TITLE
Only first page of Pokédex entry can be read with new catch

### ISSUE THREAD

**Issue by ProfEibe** [Rangi42/polishedcrystal#627]
When catching a new Pokemon and the pokedex entry opens, it is not possible to read the second page. Pressing A exits the pokedex but should first switch to the second side.

**Comment by FredrIQ** [comment]
Change the text autoscroll option to something other than A or B.

**Comment by ProfEibe** [comment]
hm I haven't thought about that, thanks for the idea.

**Comment by exelotl** [comment]
I'm having this issue, guess the Pokédex needs a small delay on the 2nd page or something so that text autoscroll doesn't skip it?
