### ISSUE TITLE
Send gift Eevee to box and Eevee's mail to PC mailbox

### ISSUE THREAD

**Issue by itsdarsh** [Rangi42/polishedcrystal#628]
Currently, gift Eevee cannot be deposited into the box when the party due to having mail. There needs to be a new script function to allow mail to be sent directly to the box if Eevee (or indeed any other gift mon) were sent to the box.

Kenya cannot be sent to the box due to the mail being a needed part of the quest, so just explain why Kenya can't be deposited.

**Comment by Rangi42** [comment]
Bill and the guard should already have checks for if the party is full, and not give you the Pokémon in that case. Character-wise, neither would want their Pokémon to go straight into the PC.

**Comment by itsdarsh** [comment]
That's how it currently is. @FredrIQ suggested being able to send Eevee to the box so I listed the idea here but there's really no way we can just send Kenya to the box. If you don't want any mail mons to go to the box then feel free to close this
