### ISSUE TITLE
Professor Oak's PKMN Talk can cause a crash if NUM_GRASSMON is changed

### ISSUE THREAD

**Issue by pigeon-crystal** [Rangi42/polishedcrystal#629]
the use of "and NUM_GRASSMON" in line 242 of engine/pokegear/radio can cause a crash if not changed to maskbits NUM_GRASSMON.
The attached image can explain it better than I can, so I'll let pfero explain:

[](https://i.imgur.com/sbfOhsU.png
)

**Comment by pigeon-crystal** [comment]
The image wasn't included. let me try that again.
https://i.imgur.com/sbfOhsU.png

**Comment by itsdarsh** [comment]
There's honestly a lot of `and 3` that should be `maskbits 3` too, but I'll save that for another day.
