### ISSUE TITLE
Remove slot machine biases

### ISSUE THREAD

**Issue by m-orsh** [Rangi42/polishedcrystal#641]
Game corner slot machines by default have biases that prevent the player from lining up symbols on the third reel unless a bias for the symbol is currently set on the current roll of the wheels. It'd be a lot more bearable in polished crystal to play the slots if the timing was actually 100% based on your skills, rather than whether the game decides it will allow you to line up symbols in the background. 1% chance of jackpot bias on the lucky slot machine is ridiculous. At that low a rate, 300 coin payouts for a jackpot is pathetically low. I feel like players would enjoy the game corner more if the slots were timing-based, rather than RNG-based. The TMs or pokemon you get from obtaining a large amount of coins aren't exactly game-breaking even if obtained early on considering the difficulty of polished crystal, so why not?

I realize real casinos aren't timing-based. This is a game, the game corner is a curiosity, mostly a miserable one in RBY and GSC due to the sadistic way the slots were programmed. I think getting rid of that sadism would be more fun for players. And the huge sum to buyout the rewards is no longer hanging over players heads like a debt they must pay since it's so hard to obtain any considerable amount of coins through the game corner games.

I imagine removing code that makes the slots do anything other than "stop the damn slot tumbler when the player presses the damn button" will reduce the amount of code needed for them as well.

**Comment by FredrIQ** [comment]
This would trivialize getting the prizes. A better approach, if we want to mess with the game corner, is to either make player-biased bonuses akin to 3-4gen, or to make the slot machines behave more like modern real life ones with the ability to set a custom bet amount (although this would probably make the slot machine system a bit too real...)

**Comment by m-orsh** [comment]
It should be trivialized, because there is nothing fun about converting your entire savings to coins every playthrough to buy a TM, and feels like a broken way of winning prizes, instead of actually playing the games intended to reward a user with coins. The difference would be now skill determines whether a player is rewarded with a piddly amount of coins, rather than how much money they have to convert because playing slots is completely a waste of time.

All the game corner experience does is detract from both pokemon RBY / pokemon GSC due to the pointlessness of actually trying the minigames in the long run due to the combination of their tiny payouts and sadistic odds, compared to simply converting your money to coins directly. It feels like a broken system when the best option is to not use the actual mini games.

**Comment by aaaaaa123456789** [comment]
> This would trivialize getting the prizes. A better approach, if we want to mess with the game corner, is to either make player-biased bonuses akin to 3-4gen, or to make the slot machines behave more like modern real life ones with the ability to set a custom bet amount (although this would probably make the slot machine system a bit too real...)

As it stands, the slot machines have a payback rate above 100%, so getting prizes is already trivial. It's just extremely grindy.
