### ISSUE TITLE
Choice Scarf does not apply speed boosts.

### ISSUE THREAD

**Issue by AnotherMindGamer** [Rangi42/polishedcrystal#645]
During my playthrough, I had a choice scarfed Primeape with 150 speed be outsped by Karen's Houndoom. Later, that same Houndoom was outsped by a ninetails with 161 speed. Initially, I assumed there was conflict with Gorilla Tactics, but I had the same results after using an ability capsule to give Primeape anger point. I then tested a Bellossom with 84 speed against Karen's Umbreon. Bellossom was outsped but an Entei with 124 outsped Umbreon. 1.5 multiplier from Choice Scarf should result in 126 speed for Bellossom, but the Bellossom with choice scarf was outsped.

Additionally, I can confirm that Gorilla Tactics is applying a power boosts. Close Combat from Primeape is a 2hko with anger point against Karen's Umbreon instead of a 1hko with Gorilla Tactics. I did not have a choice band to test.

Originally I was playing 3.0.0-beta-b23a9855, but the problem persists after changing to 3.0.0-beta-c6cbf57e. Both were the standard and not the faithful versions.

**Comment by itsdarsh** [comment]
Good catch, thank you for the detailed documentation. This should be fixed when the next build goes live within a few minutes.
