### ISSUE TITLE
Baton Pass does not maintain Mean Look

### ISSUE THREAD

**Issue by Djent-** [Rangi42/polishedcrystal#646]
According to [Bulbapedia](https://bulbapedia.bulbagarden.net/wiki/Mean_Look_(move)#Generation_II), the effects of Mean Look should should still apply after the user switches out with Baton Pass. I am using Murkrow for this (Baton Passing to a Soundproof Electrode against Entei/Raikou to prevent Roar). My testing shows this does not work, as the roaming Pokemon can still flee after the user is Baton Passed.

I am using release 3.0.0 beta 468c9dd6

This was the best strategy I could come up with as Jynx no longer has Lovely Kiss

**Comment by FredrIQ** [comment]
Baton Pass no longer preserves Mean Look starting with 5gen. Polished Crystal, which has a modernized battle engine, adapts this feature.

**Comment by Djent-** [comment]
Thanks for the explanation. I will close this issue

Sing in faithful retains its 55% accuracy however. I will rework to use Sleep Powder and perhaps suggest a paragraph for the [Roaming Pokemon wiki page](https://github.com/Rangi42/polishedcrystal/wiki/Roaming-Pokemon)
https://github.com/Rangi42/polishedcrystal/blob/eb16651b3d9490a4bea7d6e0043789a288c19d26/data/moves/moves.asm#L74
