### ISSUE TITLE
Female gift Pokémon can be shown as male on the nicknaming screen

### ISSUE THREAD

**Issue by earthoul** [Rangi42/polishedcrystal#647]
e.g. Clefairy from Goldenrod Game Corner

![2021-09-05 00 43 03](https://user-images.githubusercontent.com/7924788/132100456-11cca03b-c899-4533-a936-8ccfb3eace3e.png)

![2021-09-05 00 43 30](https://user-images.githubusercontent.com/7924788/132100454-e3baf212-ae94-4463-9f06-454b0f21494b.png)

Found in-game first by `@pengubani` from `#questions`; confirmed at a5e047e

(Sorry if it's already fixed in 9-bit)

**Comment by earthoul** [comment]
Similar reports from `@Judahnese` from `#bugs`: Eevee from Bill

![image](https://user-images.githubusercontent.com/7924788/132292841-ceb22758-43d7-419c-bbbd-a66381d528c5.png)

![image](https://user-images.githubusercontent.com/7924788/132292873-df8ff4c1-c50f-4e1b-86f8-fc2a2f060527.png)

**Comment by itsdarsh** [comment]
There's also an issue where the PC name can be glitched when getting a gift pokemon, so I'll have to investigate that as well.

**Comment by itsdarsh** [comment]
This is still bugged on master, but it's fixed on 9bit.
