### ISSUE TITLE
Goldenrod game corner gives both pokemon and coins back when party full

### ISSUE THREAD

**Issue by jvs3** [Rangi42/polishedcrystal#656]
I have a complete team of 6 pokemon and tried to exchange coins for a pokemon in the goldenrod game corner. Box 3 on the pc had 11 pokemon at this time and was not full. The dialogue is:

Here you go!
Name received Abra.
Give a nickname to the Abra you received. -> No
Abra was sent to Box 3.
Oh, no. You can't carry any more and your box is full.
I'll return your coins to you.

After this I have received an Abra in Box 3 but no coins have been substracted. It seems something goes wrong after showing the 'Abra was sent to Box 3.' message.

**Comment by jvs3** [comment]
Something similar happens with Prof. Elm's aide in the Violet City pokemon center. When you meet him to get the egg and your party is full the aide says you can't take it but the egg is transfered to the pc anyway. After this you can ask again to receive multiple eggs in the pc.

**Comment by itsdarsh** [comment]
I can't reproduce this.
