### ISSUE TITLE
Togetic doesn't evolve

### ISSUE THREAD

**Issue by pkubaj** [Rangi42/polishedcrystal#659]
I'm playing the latest 3.0 snapshot at 9fb7d6b with mgba 0.9.2. Per https://github.com/Rangi42/polishedcrystal/blob/master/data/pokemon/evos_attacks.asm, Togetic should evolve when holding the Shiny Stone.
However, mine holds one, but doesn't evolve. I found at https://github.com/Rangi42/polishedcrystal/blob/master/data/pokemon/valid_levels.asm#L122 the game seems to assume that Togetic can be max. at lvl 39. Mine is that 52. Could that be an issue?

**Comment by pkubaj** [comment]
Hm, I bumped the limit like that:
```
diff --git a/data/pokemon/valid_levels.asm b/data/pokemon/valid_levels.asm
index 12841653c..478977db0 100644
--- a/data/pokemon/valid_levels.asm
+++ b/data/pokemon/valid_levels.asm
@@ -119,8 +119,8 @@ ValidPokemonLevels: ; for Wonder Trade
        db   1,  31 ; Horsea
        db  32,  54 ; Seadra
        db   1,  19 ; Togepi
-       db  20,  39 ; Togetic
-       db  40, 100 ; Togekiss
+       db  20,  59 ; Togetic
+       db  60, 100 ; Togekiss
        db   1,  32 ; Staryu
        db  33, 100 ; Starmie
        db  20, 100 ; Mr. Mime
```

But it didn't change anything...

**Comment by walkawayy** [comment]
You have to use the Shiny Stone. Not hold it.
`EVOLVE_HOLDING` means holding an item.
`EVOLVE_ITEM` means using an item.
