### ISSUE TITLE
Regression from 2.2.0 = Stuttering display upon a wild Pokemon encounter. (beta 3.00 bug)

### ISSUE THREAD

**Issue by MetalMaxMX** [Rangi42/polishedcrystal#688]
This is a bit of a graphical bug (or perhaps intended behavior?) that I was able to reproduce with some of the most accurate gameboy emulators out there (Sameboy, mGBA, bgb). 

When you encounter any wild Pokemon, at least from what I could find in the starting town is that the behavior from when they're about to enter has some mismatches or weird graphical 'stuttering' so to speak. The movement doesn't feel natural or something is being skipped. I was able to boot up 2.2.0 and I can confirm that this stuttering when the wild PKMN is about to enter does not happens, nor in Red++ or other hacks or similar pedigree. 

The release from both the Github page and the compiled version both gave me this exact same issue so I'm reporting it here in case someone finds why that happens. 

(This was on Master)

EDIT: Just tried and built the 9-bit repo. It's also affected there as well

Cheers!
MetalMaxMX.

**Comment by Rangi42** [comment]
When the wild enemy slides to the right and your trainer slides to the left, it looks smooth to me. You're probably perceiving something different about the 60fps frame rate.

**Comment by FredrIQ** [comment]
Fixed in 65b1137b4f0eaa676c3e35f4278eeeacb011f895
