### ISSUE TITLE
[3.0.0 beta] Getting bug warning when played on a 3DS Virtual Console injection (.cia)

### ISSUE THREAD

**Issue by AkitoCL** [Rangi42/polishedcrystal#689]
Been playing this on a 3DS for quite some time and everything has worked perfectly so far. I'd suggest making the alert message something you just see ONCE instead of everytime. Isn't much of a big deal but may become annoying in the long run.
The RTC seems to work fine as a VC Injection on a 3DS.

**Comment by FredrIQ** [comment]
Fixed in 9bit with a different emulator check.
