### ISSUE TITLE
Allow consolidated moves (e.g. "Fury Strikes") to display canon names on a per-PKMN basis.

### ISSUE THREAD

**Issue by etdv-thevoid** [Rangi42/polishedcrystal#697]
### Introduction

Due to 8-bit index restrictions (256 limit), Polished Crystal has four (4) "new" moves that are consolidations of two (2) or more canon moves with similar effects and/or attributes. These are as follows:

- Fury Strikes (Fury Swipes & Fury Attack)
- Defense Curl (Defense Curl, Harden, & Withdraw)
- HealingLight (Synthesis, Morning Sun, & Moonlight)
- Fresh Snack (Softboiled & Milk Drink)

---

### Consolidated Move Animations

However, each move still plays the appropriate animation on a per-PKMN basis (i.e. Softboiled animation is used for Chansey, and Milk Drink for Miltank). For the first two moves, Fury Strikes & Defense Curl, the associated lookup tables to determine which animation to use are here:

- [`data/pokemon/fury_attack_users.asm`](../blob/master/data/pokemon/fury_attack_users.asm)
- [`data/pokemon/withdraw_harden_users.asm`](../blob/master/data/pokemon/withdraw_harden_users.asm)

The code that determines which animation to play exists in [`engine/battle/effect_commands.asm`](../blob/master/engine/battle/effect_commands.asm) and can be found by searching for the appropriate words. The snippet below is the code for determining which "Fury Strikes" animation to use:

```
; Fury Swipes and Fury Attack were merged into Fury Strikes, so use the correct
; animation for the Pokémon that learned each one
.fury_strikes
	push de
	ldh a, [hBattleTurn]
	and a
	ld a, [wBattleMonSpecies]
	jr z, .got_user_species
	ld a, [wEnemyMonSpecies]
.got_user_species
	ld hl, FuryAttackUsers
	call IsInByteArray
	pop de
	jr nc, .multihit
	ld a, $2
	ld [wKickCounter], a
	jr .fury_attack
```

This code works by using the `wKickCounter` parameter for move animations (in vanilla pokecrystal, this is used to make multi-hit moves have altering animations per hit by changing the parameter on each hit). Each sub animation corresponds to a canon move. Here, "Fury Strikes" users who would canonically know the move Fury Attack use subanimation $2 which looks like vanilla Fury Attack.

---

### Retrieving Move Names

Move names are retrieved from ROM into `wStringBuffer1` to be printed onto the screen in the following places:

- [`ListMoves:` in `engine/pokemon/mon_stats.asm`](../blob/master/engine/pokemon/mon_stats.asmmon_stats.asm#L645)
- [`GetMoveName::` in `home/names.asm`](../blob/master/home/names.asm#L181)

In both of these snippets, the move's ID constant is loaded into `wCurSpecies` and MOVE_NAME is loaded into `wNamedObjectTypeBuffer`; and then `GetName:` is called. The MOVE_NAME constant corresponds to the `NamesPointers::` entry for [`MoveNames::`](../blob/master/data/moves/names.asm). `GetName:` then retrieves the Nth entry in the list, which will be the correct name. This name is returned to the original calling routine inside `wStringBuffer1`, ready to be printed to the screen.

---

### Use Canon Move Names on a Per-PKMN Basis

I propose editing the code in `ListMoves:` and `GetMoveName::` to make similar checks so that not only do we change the animation, but also the displayed move name. The end goal would be such that to the player, it would appear as if no moves were removed and no new moves were added. Squirtle would know Withdraw, Metapod would know Harden, and Jigglypuff would know Defense Curl. But internally, these would all be the same move entry.

#### Preliminary Steps Towards Completion:

- [ ] Change consolidated moves' default names back to the canon names for their default animation.
- [ ] New globally accessible lookup lists for the variable names associated with each consolidated move's variable animation.
- [ ] Change the `ListMoves:` code to have access to the current PKMN in a memory register, and make similar checks such as those in [`engine/battle/effect_commands.asm`](../blob/master/engine/battle/effect_commands.asm) against our new variable names tables.
- [ ] Do the same thing in `GetMoveName::`
- [ ] Verification & Testing

#### Considerations:

These proposed changes involve $HOME, so ROM space immediately becomes a concern. Any new code added to [`GetMoveName::` in `home/names.asm`](../blob/master/home/names.asm#L181), space permitting, must be highly optimized.

#### Future Impact:

These changes, if implemented could then be expanded to more moves. For example, moves like Tackle and Scratch could be consolidated into one move entry. And then have it canon name and animation played depending on the user.

**Comment by Rangi42** [comment]
Thanks for your detailed proposal! I considered doing this when I initially merged those moves together. The main reason I didn't was that this workaround would be revealed by users of Sketch and Transform. It also could not apply to moves in contexts where there is no user of the move yet, like TMs and move tutors (Defense Curl has a tutor). I'd rather just wait and see if we can implement 10-bit moves.
