### ISSUE TITLE
Surf not super effective against Charizard

### ISSUE THREAD

**Issue by KoNeko1192** [Rangi42/polishedcrystal#699]
When battling the dragon tamer on Route 45, using Surf on his Charizard did not do super effective damage or display the "it's super effective!" text. I had my red Gyarados use Surf when I noticed this issue on 3.0.0.

**Comment by onirose1327** [comment]
Are you playing on the Faithful version?

**Comment by Rangi42** [comment]
Charizard is Fire/Dragon unless you play the Faithful ROM.
