### ISSUE TITLE
[9bit] Onix uses wrong Defense Curl animation.

### ISSUE THREAD

**Issue by etdv-thevoid** [Rangi42/polishedcrystal#700]
When using Defense Curl, Onix uses the Withdraw animation, and not the Harden animation. According to [`withdraw_harden_users.asm`](https://github.com/Rangi42/polishedcrystal/blob/9bit/data/pokemon/withdraw_harden_users.asm), Onix should use the Harden animation. This occurs on both sides of the battle engine: player and enemy.

![image](https://user-images.githubusercontent.com/9028176/177556160-544c9d55-8be8-45f1-b8d4-552329da3841.png)

**Comment by Rangi42** [comment]
Kabuto should also be using Harden but uses Defense Curl:
![image](https://user-images.githubusercontent.com/35663410/179765009-857d8ea7-33f6-4033-8a95-7a3e176ca081.png)

**Comment by Rangi42** [comment]
Just changing `inc hl ; ld hl, HardenUsers` to `ld hl, HardenUsers` (or `inc hl / inc hl` would be the same, since the list ends with `dw` now) doesn't work.

**Comment by rik-smeets** [comment]
Another example, just in case it might help fix this issue: when Phanpy uses Defense Curl, it shows the Withdraw animation. When it evolves into Donphan, the animation becomes correct.

**Comment by etdv-thevoid** [comment]
Its probably an obvious possibility. But to confirm the possibility, I had this same bug happen last night with against a trainer battle Beedrill & Fury Strikes. It did not use the Fury Attack animation but used the Swipes animation.

**Comment by FredrIQ** [comment]
Fixed
