### ISSUE TITLE
Trading is broken

### ISSUE THREAD

**Issue by Eragon615** [Rangi42/polishedcrystal#706]
My wife and I are playing through on the My OldBoy! emulator on android, which supports the GB Link Cable functions. We thought we'd give trading a try. We're both on the nightly beta, polishedcrystal-3.0.0-beta-bd9eea7f.gbc to be exact. 
Trading looked fine, but it seemed to duplicate other pokemon in our parties instead of yielding the expected results. For example:
We traded Nidoran♀ for Nidoran♂. The trade looked good, and the correct sprites traveled the link cable in the animation. But after it showed I had two copies of a Chikorita I had in my party, and neither Nidoran. Likewise, my wife duplicated an Eevee she had in her party, but both Nidoran were gone. On exiting the trading location, I notice a few other odd details. My second Chicorita had the Nidoran♂ sprite, and had it's Hidden Ability, where the original copy had ability 2. 

I'm pretty sure trading is going to be an incredibly niche thing, but it'd be cool if it worked. Either that or maybe block off the ability to use it?

**Comment by FredrIQ** [comment]
Known bug. This has been fixed in the upcoming "9bit" update which is to be released hopefully somewhat soonish.
