### ISSUE TITLE
Tower Tycoon / Factory Head not challenged after 21 wins

### ISSUE THREAD

**Issue by ItsKipz** [Rangi42/polishedcrystal#720]
Having a strange issue where after completing the 20th win in the Battle Tower or Battle Factory, the intended challenge with Palmer / Thorton does not happen and I instead get a normal 21st battle. I thought the battle was maybe intended to happen *after* that, but once the 21st battle is complete I immediately return to the lobby. The same issue occurred in the Factory at 42 wins as well, and I'm currently working through the Tower to see if it happens at 42 there. 

If this is helpful information, I'm playing on the latest nightly Faithful build, using the Gambatte emulator in RetroArch.

**Comment by FredrIQ** [comment]
Fixed

**Comment by unclele1** [comment]
However,Tower Tycoon's group is unused
