### ISSUE TITLE
Mention `nortc` in the FAQ and/or provide a nightly build

### ISSUE THREAD

**Issue by eievui5** [Rangi42/polishedcrystal#726]
I've been playing this hack on my Everdrive x5, which does not have an RTC. It would be nice if the game had an option to pass time while playing rather than using the RTC (namely by just incrementing the minutes every couple of steps). This would also be useful for anyone who only plays the game at a certain time of day, or for a potential 8MiB branch, since MBC5 doesn't have an RTC.

**Comment by JustRegularLuna** [comment]
There is already an option for this. The compile option "nortc" is there for flash carts and emulators without rtc support.

**Comment by eievui5** [comment]
Oh, thank you! Maybe that should be mentioned in the FAQ then?
