### ISSUE TITLE
Bump to match upstream repo as much as feasible

### ISSUE THREAD

**Issue by WSLUser** [Rangi42/polishedcrystal#747]
As this is a fork of the original https://github.com/pret/pokecrystal, it would make sense to ensure it stays updated from all the work being done there. In particular I noticed `main.asm` is seriously outdated but all the matching files are outdated too.

**Comment by Rangi42** [comment]
main.asm was reduced to just INCLUDEs a long time ago, just like pokecrystal.

**Comment by WSLUser** [comment]
Yes but I've noticed updated to those INCLUDEs and other files that don't appear to be matching and could potentially be missing things uncovered in the disassembly work being done in pokecrystal.

**Comment by Rangi42** [comment]
Feel free to open a pull request porting more of pokecrystal's improvements (although some of them over the last few years originated in polishedcrystal and were then made in pret).
