### ISSUE TITLE
Ensure all pokemon have same moves available as from Pokemon Legends: Arceus

### ISSUE THREAD

**Issue by WSLUser** [Rangi42/polishedcrystal#748]
All pokemon which exist in Crystal that also exist in Arceus should have same moves available such as Pikachu, Raichu, Eevee (all forms), and Munchlax/Snorlax. Moves like Giga Impact  and Iron Head are likely not included. (These moves should also be applied to Pokemon that makes sense. Steel pokemon for example like Steelix should have Iron Head, not just Iron Tail.)

**Comment by Rangi42** [comment]
No they shouldn't, Legends:Arceus has different battle mechanics (strong/agile styles, no abilities, freeze+sleep became frostbite+drowsy, etc) that justify different moves. Learnsets will need reconsideration after 10-bit moves.

**Comment by WSLUser** [comment]
Yeah I wasn't asking about adding the Agile/Strong style. Just the moves themselves. Also wasn't suggesting changing effects like the freeze and sleep.

**Comment by WSLUser** [comment]
Basically I want to ensure all the pokemon usable here have a bunch of moves they can use that they likely couldn't in the original Crystal like what you're able to purchase from the Security Corp leader in Arceus. I know I saw some moves I wouldn't of expected certain pokemon to be able to learn but were able to and want to ensure I have the same options available here as much as possible.
