### ISSUE TITLE
Quick Powder reported issue

### ISSUE THREAD

**Issue by Rangi42** [Rangi42/polishedcrystal#749]
> I'm pretty sure there should be a `ld a, [hl]` above the `cp DITTO` on line 389 of engine/battle/core.asm. As of now I think it's comparing the `DITTO` value against what is in register `a` which would still be the value for whose turn it is.

**Comment by FredrIQ** [comment]
9bit refactored species-specific battle items (to simplify handling given that species are no longer just 8 bits), which makes this issue, if valid, obsolete. Thanks either way!
