### ISSUE TITLE
Ghost type is immune to the bound status, not only to its trap effect

### ISSUE THREAD

**Issue by earthoul** [Rangi42/polishedcrystal#750]
Ghost-type Pokémon should only negate the trapping effect done to them and should still take the bound status and the end-of-turn damage by it, but they're currently immune to the status altogether.
e.g. When a wild Gastly is hit by Fire Spin, nothing happens after the main damage.

First found by `@Dr. Intolerance PHD` in `#bugs`, probably in the 8bit build; later by me in 9bit

**Comment by FredrIQ** [comment]
Fixed in 6c3f9781ffe9786c778174984beee106b9642023.
