### ISSUE TITLE
Money saved by mom can be carried over into new game?

### ISSUE THREAD

**Issue by frezgle** [Rangi42/polishedcrystal#753]
Started a new game after playing a couple hours in because Bugsy is a Nuzlocke ender. :')
In my first trainer battle in the new file Mom called and said she bought something, and after getting the option to save money I find out I have about $1700 saved up already. My assumption is it carried over from the old file but either way it's still way more than what I should have at this point.
I did _not_ have New Game+ unlocked; I don't have my old Pokemon or held money amount. I was playing in Nuzlocke mode, if that matters.

**Comment by Rangi42** [comment]
What version were you playing? When did you download the ROM?

**Comment by frezgle** [comment]
Sorry, should have mentioned that in the OP post! I'm on the latest nightly as of right now (8220a77e). Did not transfer from an old version at any point.

**Comment by itsdarsh** [comment]
Fixed in 9bit
