### ISSUE TITLE
Maybe Run Away should allow the Pokemon to always switch out...

### ISSUE THREAD

**Issue by Durandbolg** [Rangi42/polishedcrystal#757]
...even if under the effect of a trapping move or ability. Yes, I know that's not how it works in the actual games, but it would give the ability some actual gameplay utility. Seems to me like always being able to switch out would make Run Away a fairly useful ability to have.

**Comment by itsdarsh** [comment]
This will get implemented for non-faithful builds

**Comment by FredrIQ** [comment]
Added in 9d9251b84219e.
