### ISSUE TITLE
Inconsistent sprite colors when catching a Pokémon

### ISSUE THREAD

**Issue by roukaour** [Rangi42/polishedcrystal#77]
Glitch Kitty: "When I catch a pokemon its image that appears in the "Do you want to give a nickname to X" screen is of a colour different from its stats picture and  different from the default colour used in the pokedex image.  Basically pokemon have 3 different colours: the one they have in battle, the one in the nickname screen and the one in the pokedex..."

![image](https://user-images.githubusercontent.com/1761576/27363061-1d75dbb6-5600-11e7-8dfb-2def79447996.png)

**Comment by Rangi42** [comment]
CiriousJoker: "I just caught a Weepinbell and its Pokedex entry appeared normally […] Just caught a Kingler and its Pokedex entry was shiny, too. Most Pokemons are normal though"

![image](https://user-images.githubusercontent.com/35663410/51079159-39109300-1690-11e9-9c79-a78aa2637cd0.png)
