### ISSUE TITLE
Crystal Onix

### ISSUE THREAD

**Issue by N3rd1n5id3** [Rangi42/polishedcrystal#774]
Is it possible add Crystal Onix?

**Comment by greedlo** [comment]
If you wanted to differentiate it from the regular Onix/Steelix, you could make it a fairy ground type. 

As other crystal Pokémon we have had have been fairy type as well.

**Comment by itsdarsh** [comment]
It's definitely possible, but it's up to Rangi if we do add it, From Bulbapedia:

> Besides being made of crystal, the Crystal Onix is also unique from other Onix in that it can live in water without being hurt by it. Its glass skin also gives it a special resistance to Water-type attacks. Mateo realized that he would have to use a different type of attack to weaken it and so, he used his Charmeleon and attacked it with Fire Spin. It seemed to have a weakness to Fire-type attacks, unlike other Onix.

If anime accuracy is important in this case, it would make sense as an Ice/Ground variant with... Water Absorb?

**Comment by Rangi42** [comment]
This was done for Orange.
