### ISSUE TITLE
[Regression] Struggle can once again be disabled if you only have one move

### ISSUE THREAD

**Issue by f-raZ0R** [Rangi42/polishedcrystal#793]
#455 seems to have become unfixed, if you struggle due to your only move being disabled, you will be unable to even struggle.

This issue was reproduced on the 9bit branch.

Steps to Reproduce:
-Send out a pokemon that only knows one move, either by deleting all of its other moves at the move deleter, or naturally only knowing one move (e.g Unown).
-Use that move, and then have it get Disabled.
-Select Fight, and the game will erroneously not let you use Struggle, saying that "struggle was disabled".

Expected Behavior:
-The pokemon, without a valid move, would successfully use Struggle.

Image(s):
![image](https://user-images.githubusercontent.com/30442287/216793657-50a51385-7b86-4e9c-9f2c-860893d1f894.png)

**Comment by FredrIQ** [comment]
Fixed in d2d28be109fad4631c8661.
