### ISSUE TITLE
Indirect dynamic overworld OB and/or BG palettes

### ISSUE THREAD

**Issue by Rangi42** [Rangi42/polishedcrystal#799]
This is just a concept proposal, not something that's blocking PC 3.0. The existing dynamic OB palette system and unique BG palette system work well enough for expected additional content. This is just an arguably more elegant and maybe more efficient solution.

GSC had a "predef pal" system for applying SGB palettes. [predef.pal](https://github.com/pret/pokecrystal/blob/master/gfx/sgb/predef.pal) defines a list of RGB colors corresponding to [`PREDEFPAL_*` constants](https://github.com/pret/pokecrystal/blob/master/constants/scgb_constants.asm), and [pal_packets.asm](https://github.com/pret/pokecrystal/blob/master/gfx/sgb/pal_packets.asm) defines four colors to load at a time for particular SGB screen layouts.

[pokered-gbc](https://github.com/dannye/pokered-gbc) has a similar system for overworld BG palettes. [map_palettes.asm](https://github.com/dannye/pokered-gbc/blob/master/color/data/map_palettes.asm) defines a list of palettes (each with four RGB colors) corresponding to [map_palette_constants.asm](https://github.com/dannye/pokered-gbc/blob/master/color/data/map_palette_constants.asm); then [map_palette_sets.asm](https://github.com/dannye/pokered-gbc/blob/master/color/data/map_palette_sets.asm) defines for each tileset which eight palettes it should use, in just eight index bytes.

We could use similar systems for maps' BG palettes and/or object events' OB palettes.

For maps, it would be very similar to pokered-gbc, except there would be separate morn/day/nite/dark/indoor lists of RGB colors. [data/maps/palettes.asm](https://github.com/Rangi42/polishedcrystal/blob/master/data/maps/palettes.asm) would still exist to define unique eight-palette combos for particular maps, tilesets, landmarks, etc; but each entry would be just eight index bytes, not 64 bytes of RGB colors (or 256 bytes for morn/day/nite/eve alternatives).

For object events, instead of picking eight different 4-color palettes, we'd want to pick three different individual colors. (The fourth, the transparent lightest one, would always be copied from the BG, so fading would look appropriate.) So we'd have a table of individual RGB colors (well, separate morn/day/nite/eve/dark tables), and then a table of three-color combos (e.g. `db COLOR_PEACH, COLOR_RED, COLOR_BLACK` corresponding to `PAL_NPC_RED`, `db COLOR_BROWN, COLOR_BLUE, COLOR_BLACK` corresponding to `PAL_NPC_MARLON`, `db COLOR_WHITE, COLOR_RED, COLOR_BLACK` corresponding to `PAL_NPC_ITEM_BALL`, etc).

**Comment by FredrIQ** [comment]
Is this issue still relevant after vulcandth's work?
