### ISSUE TITLE
9bit aerodactyl with unnerve hits earthquake through airballoon

### ISSUE THREAD

**Issue by Coliath121** [Rangi42/polishedcrystal#802]
When using h-arcanine against brock in the dojo, his aerodactyl with unnerve lands earthquake regardless of the air balloon. The airballoon then pops
Notably the ai doesnt care about the air balloon either. Under previous battles, the opponent would use a non ground move even if it knew one. Only once the balloon is popped would they then use a ground move

It looks like unnerve by passes more than just berries, but i defer to devs 
Thank you!

**Comment by FredrIQ** [comment]
Not exactly, but close enough. The Unnerve check was clobbering the data that was holding the held item effect. So while the check itself worked, the held item effect was overwritten with garbage. Fixed in b099881f61bdc0d90bf721b6043a90347a34a8fe.

**Comment by Coliath121** [comment]
Amazing, thank you!
