### ISSUE TITLE
In-battle party menu item icons flash the wrong color

### ISSUE THREAD

**Issue by roukaour** [Rangi42/polishedcrystal#82]
When you press B to close a Pokémon's menu in battle, the item icons flash the color of their Pokémon.

![image](https://user-images.githubusercontent.com/1761576/27505148-d61932a4-5866-11e7-9c39-8ab1e2e14f81.png)

This is also a bug in Prism.

**Comment by Acrozz** [comment]
Did you remove the pokémon gender icons?

**Comment by FredrIQ** [comment]
Legendary Pokémon don't have any gender (Well, most of them, and all of Polished Crystal's)

**Comment by Acrozz** [comment]
Whoops... I forgot that. Anyway I checked my game just to make sure and found this:
![](https://user-images.githubusercontent.com/23432421/27513125-d57d1e10-5928-11e7-8f5f-cc4f3aa1804c.png)

**Comment by roukaour** [comment]
My fix for #11 erased genders by accident. It's fixed now.

**Comment by roukaour** [comment]
@FredrIQ Please keep an eye out for if Prism fixes this.
