### ISSUE TITLE
cant get secret medicine 

### ISSUE THREAD

**Issue by StreetRaccoon** [Rangi42/polishedcrystal#841]
ive spoken to to jasmine, beat chuck but still the pharmacy doesnt give secret medicine

**Comment by itsdarsh** [comment]
Cannot replicate this. What build are you on? Did you mess around with cheats or save states? Without more details, I'll just close this.

**Comment by StreetRaccoon** [comment]
im using the 3.0, im playing on retroarch on vita i dont use cheats or save states

**Comment by StreetRaccoon** [comment]
switched cores and i fixed the issue
