### ISSUE TITLE
Prism bonus soundtracks have a song named incorrectly

### ISSUE THREAD

**Issue by earthoul** [Rangi42/polishedcrystal#844]
https://github.com/Rangi42/polishedcrystal/blob/dba76d2a349b2ea3d04f53853b4c33d669c41bd4/audio/music/prism/trainerbattle.asm#L1-L3

https://github.com/Rangi42/polishedcrystal/blob/dba76d2a349b2ea3d04f53853b4c33d669c41bd4/data/music_player/song_info.asm#L197

(cited from 9bit)

One of the Prism bonus soundtracks, `trainerbattle.asm` by GACT, is named as such and is called "Vs.Naljo Trainer" in the music player. Actually, however, that's a battle theme of "Battle Arcade," the end-game battle facility in Naljo where players battle against "Battle Arcade PC" instead of human opponents.

Since Prism has another exclusive song for Naljo trainer battles, this needs fix on the file name, the song title, and the constant label(s) (or more).

FIQ suggests:
> FIQ: I'd just say "Arcade Battle" or similar

**Comment by aaaaaa123456789** [comment]
The song used to be the Naljo trainer song, but it was due to be deleted because many people in the team didn't like it. At the time, I was writing the Battle Arcade. I liked the song, so I moved it there.

**Comment by FredrIQ** [comment]
Fixed in 85c1b90b9ece621c.
