### ISSUE TITLE
Question: Can you evolve a pokémon with high friendship at level 100 in Polished Crystal?

### ISSUE THREAD

**Issue by Realtimeless785** [Rangi42/polishedcrystal#854]
Can you evolve a Pokémon with high friendship at level 100 in Polished Crystal?

For example: Chansey, that evolves into Blissey when the friendship is 220 or higher

Will Rare Candy evolve my Lv. 100 Chansey into Blissey?

**Comment by itsdarsh** [comment]
Yes. In the future, please ask questions like this on Discord.
