### ISSUE TITLE
No Effect From Light Ball/Thick Club

### ISSUE THREAD

**Issue by TAG1Kilo** [Rangi42/polishedcrystal#859]
Using a debug version of 9-bit (compiled 6/19/23), I tested the damage output of physical and special moves for two forms of Pikachu holding Light Ball, and physical moves for the Cubone line holding Thick Club. Here are some numbers I recorded that heavily indicate that the item effects are not working:

==Light Ball==
Using a Lv57 Regular Pikachu...
With Light Ball:
Thunderbolt vs Teacher Kathryn's Lv66 Bellossom
18 damage before roll
Wild Charge vs Teacher Kathryn's Lv66 Bellossom
17 damage before roll

Without Light Ball:
Thunderbolt vs Teacher Kathryn's Lv66 Bellossom
18 damage before roll
Wild Charge vs Teacher Kathryn's Lv66 Bellossom
17 damage before roll

Using a Lv57 Flying Pikachu...
With Light Ball:
Thunderbolt vs Teacher Kathryn's Lv66 Bellossom
16 damage before roll
Wild Charge vs Teacher Kathryn's Lv66 Bellossom
17 damage before roll

Without Light Ball:
Thunderbolt vs Teacher Kathryn's Lv66 Bellossom
16 damage before roll
Wild Charge vs Teacher Kathryn's Lv66 Bellossom
17 damage before roll

The lack of any change in damage, even despite the level difference, indicates some kind of problem with the code. Neither the special attack, nor physical attack boost appear to be working for different forms of Pikachu.

==Thick Club==
Using a Lv40 Cubone...
With Thick Club:
Bonemerang vs Hiker Anthony's Lv12 Geodude
72 damage before roll

Without Thick Club:
Bonemerang vs Hiker Anthony's Lv12 Geodude
72 damage before roll

Using a Lv40 Marowak...
With Thick Club:
Bonemerang vs Hiker Anthony's Lv12 Geodude
123 damage before roll

Without Thick Club:
Bonemerang vs Hiker Anthony's Lv12 Geodude
123 damage before roll

Using a Lv40 Alolan Marowak...
With Thick Club:
Bonemerang vs Hiker Anthony's Lv12 Geodude
94 damage before roll

Without Thick Club:
Bonemerang vs Hiker Anthony's Lv12 Geodude
94 damage before roll

Again, it appears as though the item effects are not working as intended.

Given the lack of effect for both of these items, it may be wise to review the functionality for all of the items in the ".ValidBattleItemTable" in the effect_commands.asm file. However, this specific problem could be due only to light ball and thick club sharing some overlap of code (why I issued the report of them together). I'll be testing the Leek next to see if it shares the same issue.

I uploaded the rom, sav, and some save states for testing purposes if you want to try them yourselves. (The sav should have all relevant mons and items ready for use. Go wherever you want!)

[Debug ThickClub_LightBall.zip](https://github.com/Rangi42/polishedcrystal/files/11891317/Debug.ThickClub_LightBall.zip)

**Comment by FredrIQ** [comment]
Fixed, thanks for the report!
