### ISSUE TITLE
Breeding bug

### ISSUE THREAD

**Issue by QB1242** [Rangi42/polishedcrystal#866]
When breeding without Ditto, all hatched eggs are female. This makes it impossible to obtain certain egg moves.
![1](https://github.com/Rangi42/polishedcrystal/assets/139677950/473dcb62-c383-4f6c-95e8-1f776e09ff0d)
![2](https://github.com/Rangi42/polishedcrystal/assets/139677950/77cb366f-5f1f-4ae0-a018-4a9887e91cf2)

**Comment by tididaa** [comment]
Same issue happens to me. I was trying to get Rock Blast Heracross, breeding Shuckle Male and a female Heracross. Only hatched female Heracross (although with Rock Blast)

**Comment by QB1242** [comment]
After doing some more testing, this bug seems to happen whenever a female Pokemon is used, even with Ditto. The only way to get a non female egg is from Ditto + a Male Pokemon, making cross breeding egg moves impossible.

**Comment by TAG1Kilo** [comment]
Confirming the above observations. Breeding only works properly with male + ditto.

**Comment by TAG1Kilo** [comment]
Addendum: Nidoking and Nidoqueen do produce male and female eggs.

Although, the ratio doesn't seem to be 50/50 (made 48 eggs; 35 male, 13 female), despite `50 percent` being listed in `daycare.asm` under the `.GotMother` script for nidoran breeding.

**Comment by TAG1Kilo** [comment]
Breeding Ursaluna also seems to work the same way as the Nidos (it has the same 9bit species value as Nidoran_F).

Another potential bug, bot sure if it should be here or opened as something else: I accidentally told the grandpa I didn't want the egg while testing this and could not get him to generate another egg (despite having max attraction of the mons in the daycare) until I took one of them out of the daycare and put it back in. Restarting the emulator and even closing it after saving didn't fix it either. I attempted for over ten minutes. After taking out and putting a mon back in the daycare eggs starting generating almost immediately.

**Comment by itsdarsh** [comment]
> Addendum: Nidoking and Nidoqueen do produce male and female eggs.
>
> Although, the ratio doesn't seem to be 50/50 (made 48 eggs; 35 male, 13 female), despite 50 percent being listed in daycare.asm under the .GotMother script for nidoran breeding.

Just to address this, this has a 0.06% chance of occurring. Very unlikely, but not outside the realm of human possibility. I didn't change anything with the Nido code but on my own run after pushing the fix to the gender issue, I made 26 eggs and got 14 male and 12 female, which is essentially 50/50. Unless someone else raises this issue, I'm satisfied to say this isn't bugged.
