### ISSUE TITLE
Silver is in two places at once

### ISSUE THREAD

**Issue by jamescastells** [Rangi42/polishedcrystal#872]
Polished Crystal contains the same mistake seen in vanilla Crystal (not present in the original G/S):

_In Pokémon Crystal, because [Silver](https://bulbapedia.bulbagarden.net/wiki/Silver_(game)) doesn't battle the player immediately after entering the Burned Tower, the player can enter the tower and speak with [Eusine](https://bulbapedia.bulbagarden.net/wiki/Eusine), and see that Silver is in the middle of the tower, waiting for the player. However, if the player leaves and proceeds to [Olivine City](https://bulbapedia.bulbagarden.net/wiki/Olivine_City), when the player arrives Silver appears there, exiting the [Olivine Gym](https://bulbapedia.bulbagarden.net/wiki/Olivine_Gym), and then talks to the player before leaving. If the player returns to the Burned Tower, Silver will still be waiting for the player there._

A solution would be to block the player's path to Route 38 until the Burned Tower event is solved.

**Comment by Rangi42** [comment]
The player walks around; he can too.

If you think it's unrealistic for him to go back and forth from the tower to the gym and back... well, why were *you* doing it? :P
