### ISSUE TITLE
Screen blinks when failing to catch a Pokemon in the Bug-catching contest

### ISSUE THREAD

**Issue by jamescastells** [Rangi42/polishedcrystal#875]
If you're in the bug-catching contest, throw a ball at a Pokemon, and it misses, the screen blinks white for less than one second. I have attached a video:

https://github.com/Rangi42/polishedcrystal/assets/5696029/85e82177-4081-4d8e-b041-5fbc295807d4

**Comment by itsdarsh** [comment]
Fixed in 9bit
