### ISSUE TITLE
Request: add "healed point" to New Bark Town after beating the league

### ISSUE THREAD

**Issue by jamescastells** [Rangi42/polishedcrystal#876]
After beating the league, I was deposited into New Bark Town and Elm called me. Instead of giving me the ticket right away, he battled me, and I lost. Since my last "healed point" was Indigo Plateau, I was deposited back there. I can't fly to Johto, because I'm in Kanto. To get to Elm and progress the story, I have to go back all the way from the League to New Bark Town, without flying.

Please add a "healed point" to New Bark Town, so if I lose after the league, I'm deposited there.

**Comment by itsdarsh** [comment]
In 9bit, you can lose to Elm without whiting out, so I'll mark this as closed. It will be merged to master eventually.
