### ISSUE TITLE
Cycling Road's southern gate graphical glitch

### ISSUE THREAD

**Issue by jamescastells** [Rangi42/polishedcrystal#877]
If coming from the cycling road, the southern gate will have a water title overlapping its roof:

<img width="641" alt="image" src="https://github.com/Rangi42/polishedcrystal/assets/5696029/9cec3768-67c2-4daf-a1f8-9d30ad4ca8ed">

Walking from it and then back to it fixes it, so there's a problem in the connection between route 17 and 18.

**Comment by itsdarsh** [comment]
Fixed in 9bit
