### ISSUE TITLE
Hatched Togepi Event Trigger Bug

### ISSUE THREAD

**Issue by TAG1Kilo** [Rangi42/polishedcrystal#882]
Multiple players in the #testing-9bit channel on discord reported troubles getting Professor Elm to recognize that they had hatched the event Togepi and have it in their party to start the quest over the phone, and to collect the Odd Souvenir, as well as to actually collect it in Elms Lab. Through some collective testing, and one player's excellent sleuthing, it was determined and confirmed by several others that only male Togepi that hatch from the event egg trip the flag, and Elm will not recognize an event egg Togepi in your party if it is female. Likewise, he will only notice males of the evolutions too. This bug is replicable on a debug build of the latest commit of 9-bit (files attached).

This may be due to a problem in the code for `CompareSpeciesWithDE` and `CompareSpeciesForm` in **home/pokemon.asm** `L418`, though the problem could lie elsewhere. At least it's a place to start.
[Debug Hatched Togepi Event.zip](https://github.com/Rangi42/polishedcrystal/files/12387388/Debug.Hatched.Togepi.Event.zip)

**Comment by SeasickShore** [comment]
This has been fixed.

PR: https://github.com/Rangi42/polishedcrystal/pull/885
Commit 822a2b2

Not sure how to format this :')

@FredrIQ

**Comment by FredrIQ** [comment]
Fixed. Thanks for the report!
