### ISSUE TITLE
Interacting with Ruins of Alph sliding tile description while walking up (and bonking) briefly bugs out Trainer sprite

### ISSUE THREAD

**Issue by itsdarsh** [Rangi42/polishedcrystal#897]
More specifically, it overwrites the walking animation with the Unown alphabet for a frame.

![image](https://github.com/Rangi42/polishedcrystal/assets/55897426/f6b7dcf8-8b41-4a31-8763-b80200c70af7)

**Comment by FredrIQ** [comment]
Fixed in 078d7668d3e098753a9edbb3126b926f625ab135.
