### ISSUE TITLE
Kangaskhan top of the head pixel don't move with the rest

### ISSUE THREAD

**Issue by itsdarsh** [Rangi42/polishedcrystal#916]

**Comment by itsdarsh** [comment]
Separated this off because the issue goes a bit deeper: the whole framing (is thatthe right word) of the battle animations seem to be off by one line. see also: an enemy using zen headbutt on you. the top of the player mon sprite and name will slide with the opponent

**Comment by FredrIQ** [comment]
Fixed in ba3c756ae6a9f1fbb8990b6f5ce25660a8154ad3.
