### ISSUE TITLE
Improve Town Map/Fly menu

### ISSUE THREAD

**Issue by ScratchRZL** [Rangi42/polishedcrystal#942]
Make it so that you can move the cursor in the town map and fly menus freely like in Gen 3 and onward instead of it scrolling to the next or previous area with the up and down buttons. The way it works in Gen 2 is very inconvenient to use. Additionally, if possible, let the player fly from one region to another.

**Comment by ScratchRZL** [comment]
help how do i mark this as enhancement

**Comment by Rangi42** [comment]
Many landmarks are not on the 8x8-tile grid, and I think it would be less convenient to move a cursor onto them than to cycle through a sequence with Up/Down. Also, Flying between Johto and Kanto would make the Magnet Train and SS Aqua kind of pointless.
