### ISSUE TITLE
ez flash blue screen/ error

### ISSUE THREAD

**Issue by oscvr16** [Rangi42/polishedcrystal#943]
I recently tried almost every version of polished crystal onto my ez flash cart for my gba sp and after the game freak start screen it always goes into the blue screen error. It never advances after that and the game runs fine until that point. It never takes me to the start screen making it unplayable.

**Comment by Rangi42** [comment]
An EZ Flash JR cartridge should work; I use one. An EZ Flash Omega will *not* work; that's a GBA cartridge which plays Game Boy/Color games using the Goomba emulator, which has inaccuracies that break it on Polished Crystal (and I think even regular Crystal).

**Comment by oscvr16** [comment]
That pretty much solves it. I am using the omega version. I figured this was the issue but I read that the omegas can run GBC games as well. Thanks
