### ISSUE TITLE
FATAL: unknown option 'h'

### ISSUE THREAD

**Issue by ScratchRZL** [Rangi42/polishedcrystal#944]
rgbgfx -h -o gfx/pokedex/question_mark.2bpp gfx/pokedex/question_mark.png
FATAL: unknown option 'h'
Usage: rgbgfx [-r stride] [-CmOuVZ] [-v [-v ...]] [-a <attr_map> | -A]
       [-b <base_ids>] [-c <colors>] [-d <depth>] [-L <slice>] [-N <nb_tiles>]
       [-n <nb_pals>] [-o <out_file>] [-p <pal_file> | -P] [-q <pal_map> | -Q]
       [-s <nb_colors>] [-t <tile_map> | -T] [-x <nb_tiles>] <file>
Useful options:
    -m, --mirror-tiles    optimize out mirrored tiles
    -o, --output <path>   output the tile data to this path
    -t, --tilemap <path>  output the tile map to this path
    -u, --unique-tiles    optimize out identical tiles
    -V, --version         print RGBGFX version and exit

For help, use `man rgbgfx' or go to https://rgbds.gbdev.io/docs/
make: *** [Makefile:220: gfx/pokedex/question_mark.2bpp] Error 1

**Comment by Rangi42** [comment]
Use INSTALL.md's instructed version of RGBDS.
