### ISSUE TITLE
Corrupted sprites and game freezes

### ISSUE THREAD

**Issue by SOH10001** [Rangi42/polishedcrystal#965]
Ran into a few problems.

My storage box is corrupted.  It is full of dozens of boxes of "bad eggs" all of which hatch into unown.  I can still deposit and save but the text is scrambled.

The larger issue is/are the corrupted sprites which, when interacted with, freeze the game.  There are several, including sporadic trainers (which can be avoided) and the poke fan in Vermilion city and a trainer in front of Erika (which cannot be avoided).  Unfortunately, this means I am unable to progress further as the game freezes whenever I approach Erika.

Some of these issues resolve upon resetting the game.  The Erika gym and Pokefan sprites will not reset.

![Uh Oh](https://github.com/Rangi42/polishedcrystal/assets/156560088/f681de5b-3939-4839-bead-7e0f160fe3d3)
![Uh Oh 2](https://github.com/Rangi42/polishedcrystal/assets/156560088/455c9eb4-1b99-43be-afba-1764b1b9f5ee)

**Comment by FredrIQ** [comment]
Is this on mgba 0.5?

**Comment by SOH10001** [comment]
Yes, should have mentioned that too.

I don't want to move over to 0.10 as I cannot get my save file to open on it.  When I open Polished Crystal, it prompts me to start a new game.

**Comment by FredrIQ** [comment]
I cannot assist with any potential issues arising from using an inaccurate emulator.
