### ISSUE TITLE
Wich version has upgraded PokeDex?

### ISSUE THREAD

**Issue by kiltro94** [Rangi42/polishedcrystal#966]
I readed an article on a closed github issue about an upgrade to the PokeDex, how do i get this feature on my own rom? i downloaded the 3.0.0 version regular now

**Comment by vulcandth** [comment]
The upgraded Pokedex is part of `9bit`, which is a "bleeding-edge" development branch. You can either build the `9bit` branch from source, or you may find a pined link in the Polished Crystal #testing-9bit discord channel to download it.
