### ISSUE TITLE
Cant enable Mystery Gift

### ISSUE THREAD

**Issue by joshbowyer** [Rangi42/polishedcrystal#982]
How can I enable mystery gift with the iR sensor? The girl on 5F of the Goldenrod department store doesnt enable it.

**Comment by rmilejcz** [comment]
see here: https://www.pokecommunity.com/threads/pok%C3%A9mon-polished-crystal-update-2-2-0.373172/

it seems that mystery gift support was removed on an earlier release

**Comment by joshbowyer** [comment]
Damn, why remove it??

Also for the pokemon removed from the game, they can still be traded in right?

**Comment by joshbowyer** [comment]
I guess I dont know which version I have, I bought it flashed to a GBC cart

**Comment by vulcandth** [comment]
Mystery Gift was intentially removed; for general questions about the game please join the polished discord server; see the link on the readme.md
